### ISSUE TITLE
Issue while writing id3v2 tags

### ISSUE THREAD

**Issue by danieleghisi** [taglib/taglib#1008]
Hello, and thanks for this valuable project.
I am trying to use taglib to handle tags mostly on mp3 files. 

I am using essentially the same structure as in the tagwriter.cpp example. It is however unclear to me how to set/replace id3v2 tags properly. I am trying to use either 4 letter codes ("TIT3", "TCOM"...) or their verbose description as it appears in id3v2frame.cpp ("Subtitle", "Composer"...) as values in 

                                TagLib::PropertyMap map = (*it).file()->properties ();
                                if(field == 'R') {
                                    map.replace(value, TagLib::String(txtbuf));
                                }

However, they do not appear as id3v2 tags. Even worse existing id3v2 tags are no longer recognized by tools such as id3tool/id3v2 (they start to say that there are no id3v2 tags at all).

Am I doing something wrong? Can anyone point me to the right direction?

Thanks,
Daniele

**Comment by ufleisch** [comment]
When using `TagLib::PropertyMap` you should use the keys listed in the comment of the class (look into file *tpropertymap.h*), these values will be mapped to the corresponding ID3v2 frame. If you use other keys, an ID3v2 TXXX frame with the key as its description will be created.

If you want to explicitly generate ID3v2 frames, create an instance of a concrete sub class of `TagLib::ID3v2::Frame`, e.g. a `TagLib::ID3v2::TextIdentificationFrame` with "TIT3" or "TCOM" as the *type* constructor parameter, and populate the frame fields using methods of the corresponding class. Finally, use `ID3v2::Tag::addFrame()` to add the frame to the tag.

**Comment by danieleghisi** [comment]
Thanks so much for your quick answer. I have perhaps a more general doubt: even when I read the `TagLib::PropertyMap` from the `tag()` method of a generic `TagLib::FileRef f(filename->s_name)`, the ID3v2 tags do not show up. They *do* show up, however if I open the file as `TagLib::MPEG::File f(filename->s_name)` and use the `ID3v2Tag()` method.

Is this the intended behavior? As far as I understand, the `TagLib::Fileref` abstract scenario is meant to give a sort of "union" of all the tags of the file, regardless of their type (`TagLib::ID3v1::Tag`, `TagLib::ID3v2::Tag`, `TagLib::APE::Tag`, `TagLib::RIFF::Info::Tag`, etc.).

What would be a good strategy to get the different kinds of tags from a generic file? I was wondering whether there was any way to mimics for a generic file the behavior of functions like ID3v2Tag() , ID3v1Tag(), APETag(), etc., possibly returning NULL if the specific kind of tag is not implemented for the file.

I hope this makes some sense, I'm only beginning to find my way through the jungle of audio metadata :-)

Thanks so much again,
Daniele

**Comment by ufleisch** [comment]
First, you create a `TagLib::FileRef` from a file. Then use its `file()` method to get a `TagLib::File*`. You can then find out the type of file by trying to do a `dynamic_cast` to all possible sub classes of `TagLib::File`, in your case `TagLib::MPEG::File`. If you have such a pointer, you can call its `ID3v2Tag()` method to get its ID3v2 tags, and the `frameList()`. What I find a bit confusing in TagLib's API is the fact that it seems to be necessary to create a new instance after calling `save()`. Another thing which is caused by the omission of making some methods `virtual` and the need to keep this in order to remain binary compatible are some hacks which are a bit surprising when using the API (so do not rely too much on polymorphism). This is the case for `TagLib::File::properties()`, but what could be surprising too is that such a file can have multiple tags (ID3v1, ID3v2, APE in the case of `TagLib::MPEG::File`) and you will get the properties of the first tag which is present, which might not be ID3v2. So I would suggest that you call `properties()` on the `TagLib::ID3v2::Tag` instance and not on `TagLib::Tag`. If you are confused by TagLib's behavior, it may be helpful to look at the unit tests in the *tests* folder of the sources, it often documents the correct usage of the API.

**Comment by danieleghisi** [comment]
Thank you so much!

**Comment by scotchi** [comment]
One small thing to chime in there:  the `id3v2` command line tool mostly hasn't been updated in the last 20 years, and can't read the ID3v2.4 tags that TagLib writes by default (though TagLib is also able to write ID3v2.3, which that tool can read).

**Comment by danieleghisi** [comment]
I understand, thanks for pointing this out.
