### ISSUE TITLE
Fail to identify Opus files with the .ogg extension

### ISSUE THREAD

**Issue by Ambrevar** [taglib/taglib#1011]
I have Opus files with the .ogg extension and Strawberry (which leverages taglib) fails to detect them.
If I change the file extension to `.opus`, it works.

I've reported this on the Strawberry bugtracker (https://github.com/strawberrymusicplayer/strawberry/issues/712#issuecomment-835374681) and they forwarded me here.

**Comment by ufleisch** [comment]
When using the standard `FileRef(FileName fileName, ...)` constructor, it will call `FileRef::parse(FileName fileName, ...)` which will first try `detectByResolvers()`, then `detectByExtension()`, and finally `detectByContent()`. The problem here is that `detectByExtension()` will return a non null `TagLib::File*` pointer, actually an invalid Ogg/Vorbis file, and the `detectByContent()` will not be tried. This behavior could be changed by deleting the returned `TagLib::File*` if `!d->file->isValid()`, such a check for validity is also done in `detectByContent()` and should be added to `detectByExtension()` and `detectByResolvers()`.

A backwards-compatible solution would be if Strawberry implement a subclass of `TagLib::IOStream` with an improved file type detection. This could also be implemented in a way to work with TagLib versions < 1.12 because the "Enabled FileRef to detect file types based on the stream content" feature is only available in TagLib 1.12.

**Comment by Ambrevar** [comment]
@jonaski What do you think?

**Comment by ufleisch** [comment]
Should be fixed by #1013.

**Comment by Ambrevar** [comment]
Thanks!
