### ISSUE TITLE
Tests output results for taglib (acknowledgement)

### ISSUE THREAD

**Issue by JayKaku** [taglib/taglib#1016]
I ran a couple of times the unit tests with cppunit and wished to know what response shall I expect, I got no errors while running the tests but no acknowledgement if the it was successful. My question being if I get nothing printed on the console is it safe to assume the tests were successful ?

**Comment by ufleisch** [comment]
Strange, I get lots of output when running `tests/test_runner` or `ninja check` (having configured the project with CMake option `-GNinja`) on Linux. You have passed `-DBUILD_TESTS=ON` and `-DBUILD_SHARED_LIBS=OFF` (the tests seem to need static linking) when running `cmake`? What OS are you using and what command do you call to run the unit tests?

**Comment by JayKaku** [comment]
I am using Windows 10 with Visual Studio community version 2019 (MSVS) and followed the installation and unit testing guide for MSVS, as for the command, I am using the `tests\Debug\test_runner.exe` while running the unit tests

**Comment by ufleisch** [comment]
With Window 10 and Visual Studio 2019, I can run the tests with the following procedure:

```
cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=OFF ^
-DENABLE_STATIC_RUNTIME=ON -DBUILD_TESTING=ON -DCPPUNIT_INCLUDE_DIR=%cd%\..\..\cppunit\winbin\include ^
-DCPPUNIT_LIBRARIES=%cd%\..\..\cppunit\winbin\msvc\x64\ReleaseDll\cppunit_dll.lib ^
-DCPPUNIT_INSTALLED_VERSION=1.15.1 -DZLIB_SOURCE=C:/path/to/zlib-1.2.8 ..\taglib
cmake --build . --config Release
cmake --build . --config Release --target check
```

To build, you need a command prompt with `cmake.exe` in the `PATH`. I have a directory containing the taglib sources in a folder *taglib* and a build folder *msvs_build* from where these commands are started. You will have to build cppunit before and adapt the paths in the cmake arguments to point to the include and lib directories. If you want to use zlib, you will have to adapt this path too, I had to use slashes in this path instead of back slashes.

To run the tests, the directory containing the file *cppunit_dll.dll* must be in the path, in my case this was

```
path %path%;%cd%\..\..\cppunit\winbin\msvc\x64\ReleaseDll
```

Instead of using `cmake --build . --config Release --target check`, the tests can also be run using `tests\Release\test_runner.exe`.
For the Visual Studio 2019 GUI, I had to open the *taglib.sln* generated by `cmake`, build `Release, x64` and run *test_runner*.

Probably, this will work with a Debug configuration too, but then you will have to replace `Release` by `Debug` in all commands.

**Comment by ufleisch** [comment]
You can now have a look at the output of the windows-latest job of our CI: https://github.com/taglib/taglib/actions.
