### ISSUE TITLE
Taglib is very slow on loading tags from about 1464 mp3 file

### ISSUE THREAD

**Issue by MBSadeghzadeh** [taglib/taglib#1026]
I am using Qt 5.14.0, MinGW, Windows 10 and taglib version 1.1. When I load tags of about 1464 mp3 file(total size is about 4.9 GB) in parallel by 3 distinct threads, it takes about 180 seconds to complete. isn't it slow? or my expectation is high?

**Comment by MBSadeghzadeh** [comment]
My code to read tags is in below:
````

QByteArray getTagLibPath(const QString &path)
{
    return QFile::encodeName(path);
}

void DTagReader::GetTags(const QString &path, DTagInfo &tagInfo,
                         bool updateCover, bool updateRating)
{
    if (path.isEmpty())
        return;


    TagLib::File *audioFile;
    TagLib::ID3v2::Tag *tag;
    if (path.endsWith(".flac", Qt::CaseInsensitive))
    {
        audioFile = new TagLib::FLAC::File(getTagLibPath(path).constData());
        tag = dynamic_cast<TagLib::FLAC::File*>(audioFile)->ID3v2Tag(true);
        // TAGLIB::ID3V2::TAG
    }
    else if (path.endsWith(".mp3", Qt::CaseInsensitive) ||
             path.endsWith(".mpeg", Qt::CaseInsensitive))
    {
        audioFile = new TagLib::MPEG::File(getTagLibPath(path).constData());
        tag = dynamic_cast<TagLib::MPEG::File*>(audioFile)->ID3v2Tag(true);
        // ID3V2
    }
    else if (path.endsWith(".aiff", Qt::CaseInsensitive))
    {
        audioFile = new TagLib::RIFF::AIFF::File(getTagLibPath(path).constData());
        tag = dynamic_cast<TagLib::RIFF::AIFF::File*>(audioFile)->tag();
        // ID3V2
    }
    else if (path.endsWith(".ogg", Qt::CaseInsensitive))
    {
        SongInfo songInfo;
        songInfo.path = path;
        tagInfo.songInfo = songInfo;
        tagInfo.isFilled = true;
        //        delete audioFile;
        return;
    }
    else if (path.endsWith(".mp4", Qt::CaseInsensitive))
    {
        //        delete audioFile;
        //        audioFile = new TagLib::MP4::File(getTagLibPath(path).constData());
        return;
        // MP4::TAG
    }
    else if (path.endsWith(".wav", Qt::CaseInsensitive))
    {
        audioFile = new TagLib::RIFF::WAV::File(getTagLibPath(path).constData());
        tag = dynamic_cast<TagLib::RIFF::WAV::File*>(audioFile)->ID3v2Tag();
        // ID3V2
    }
    else if (path.endsWith(".wma", Qt::CaseInsensitive) ||
             path.endsWith(".asf", Qt::CaseInsensitive))
    {
        audioFile = new TagLib::ASF::File(getTagLibPath(path).constData());
        TagLib::ASF::Tag *asfTag = dynamic_cast<TagLib::ASF::File*>(audioFile)->tag();


        SongInfo songInfo;
        songInfo.title = QString::fromUtf8(asfTag->title().to8Bit(true).c_str());
        songInfo.artist = QString::fromUtf8(asfTag->artist().to8Bit(true).c_str());
        songInfo.album = QString::fromUtf8(asfTag->album().to8Bit(true).c_str());
        //        tagInfo.Year = asfTag->year();
        songInfo.comment = QString::fromUtf8(asfTag->comment().to8Bit(true).c_str());
        //        tagInfo.Track = asfTag->track();
        songInfo.genre = QString::fromUtf8(asfTag->genre().to8Bit(true).c_str());
        songInfo.path = path;
        tagInfo.isFilled = true;
        tagInfo.songInfo = songInfo;

        //        delete audioFile;
        delete audioFile;
        return;
        // ASF::TAG
    }

    if (!tag) {
        qDebug() << Q_FUNC_INFO << " tag is empty!: " << path;
        delete audioFile;
        return;
    }

    SongInfo &songInfo = tagInfo.songInfo;
    songInfo.title = QString::fromUtf8(tag->title().to8Bit(true).c_str());
    songInfo.artist = QString::fromUtf8(tag->artist().to8Bit(true).c_str());
    songInfo.album = QString::fromUtf8(tag->album().to8Bit(true).c_str());
    songInfo.year = tag->year();
    songInfo.comment = QString::fromUtf8(tag->comment().to8Bit(true).c_str());
    songInfo.track = tag->track();
    songInfo.genre = QString::fromUtf8(tag->genre().to8Bit(true).c_str());
    songInfo.path = path;
    tagInfo.isFilled = true;

    if(audioFile->audioProperties()) {
        TagLib::AudioProperties *properties = audioFile->audioProperties();
        songInfo.length = properties->length();

        int seconds = properties->length() % 60;
        int minutes = (properties->length() - seconds) / 60;

        songInfo.bitRate = properties->bitrate();
        songInfo.sampleRate = properties->sampleRate();
        songInfo.channels = properties->channels();
        songInfo.duration = QString("%0:%1").arg(minutes).arg(seconds);
    }


    // BPM
    TagLib::ID3v2::FrameList fl = tag->frameListMap()["TBPM"];
    if(!fl.isEmpty())
        songInfo.bpm = QString::fromLatin1(fl.front()->toString().toCString()).toDouble();

    // COMPOSER
    TagLib::ID3v2::FrameList flCOM = tag->frameListMap()["TCOM"];
    if(!flCOM.isEmpty())
        songInfo.composer = QString::fromLatin1(flCOM.front()->toString().toCString());

    // cover:
    if (updateCover) {
        QPixmap pixmap;
        QByteArray cover, other;
        static const char *idPicture = "APIC";
        TagLib::ID3v2::FrameList frames;
        TagLib::ID3v2::AttachedPictureFrame *apf;

        frames = tag->frameListMap()[idPicture];

        for ( auto frame : frames ) {
            apf = (TagLib::ID3v2::AttachedPictureFrame *) frame;
            if ( apf->type() == TagLib::ID3v2::AttachedPictureFrame::FrontCover ) {
                cover = QByteArray( apf->picture().data(), apf->picture().size() );
                break;
            } else {
                other = QByteArray( apf->picture().data(), apf->picture().size() );
            }
        }


        if ( !cover.isEmpty() ) {
            pixmap = QPixmap::fromImage( QImage::fromData(cover) );

        } else if (!other.isEmpty()){
            pixmap = QPixmap::fromImage( QImage::fromData(other) );

        } else {
            pixmap.load("://Icons/PlayList/song.png");
        }

        if (pixmap.width() <= pixmap.height()) {
            pixmap = pixmap.scaledToWidth(150);
        } else {
            pixmap = pixmap.scaledToHeight(150);
        }
        songInfo.cover = pixmap;
    }

    // rating
    if (updateRating) {
        int rating = 0;
        static const char *idRating = "POPM";
        TagLib::ID3v2::FrameList frames;
        frames = tag->frameListMap()[idRating];

        for ( auto frame : frames ) {
            TagLib::ID3v2::PopularimeterFrame *pf = (TagLib::ID3v2::PopularimeterFrame *) frame;

            rating = pf->rating();

            if (rating == 255)
                rating = 5;
            else if (rating != 0)
                rating = 1 + pf->rating() / 64;
        }
        songInfo.rating = rating;
    }

//    tagInfo.songInfo = songInfo;
    delete audioFile;
}
````

**Comment by scotchi** [comment]
Can you please test with the `tagreader` example from `taglib/examples`?  You'll need to build with the CMake option `-DBUILD_EXAMPLES=On`, and want to make sure you're using a release build, not a debug one.  Honestly, there are quite a few problems in your code, and it doesn't really make sense to go through them one-by-one here in TagLib's bug tracking, and it'd make more sense to use a stripped down version from our examples directory.

Also, you're probably not going to get a speedup from using multithreaded code as TagLib is primarily IO, not CPU bound.  In fact, I'd expect multi-threaded scanning to be slower, but I haven't done any extensive testing there since the world moved from HDDs to SSDs (multithreaded would definitely be slower with an HDD).

Once you have `tagreader` built, then you can run something like this:

`find ~/Music -name \*.mp3 -print0 | time xargs -0 ./tagreader > /dev/null`

For me that scans all of my 11590 file music collection in about 20 seconds.

**Comment by jonaski** [comment]
I've done extensive testing on this a long time ago, I found that running 2 jobs or more in parallel was actually slower, I was actually surprised how much slower it was too. I tested both with SSD and an older SATA mechanical drive. It has to do with disk I/O, nothing to do with taglib.
I've also compared taglib vs tagparser (https://github.com/Martchus/tagparser). The speed is exactly the same.

**Comment by MBSadeghzadeh** [comment]
@scotchi 
Thanks. I am going to test it as you said. 
would you please tell me what problems are in my code if possible?

**Comment by scotchi** [comment]
There are really too many issues to go through them individually, and it's mostly general C++ advice:

- Initialize pointers when creating them (e.g. to `nullpointer`).
- If you're using `auto`, use it consistently.  You're mixing C++99 and C++11 declaration styles.
- You're creating objects with `new` where just declaring them as (stack) variables would work just fine.
- Don't use C style casts on C++ pointers (use things like `static_cast` instead).
- It's odd to declare a pointer type on one line, and then `dynamic_cast` it on the next.  I would structure the declarations differently, but beyond that, you don't need a run-time check for the type since it's obviously known.
- And, aside from all of that, this whole block of code is basically reimplementing TagLib's `FileRef` class, which would probably be easier to use.

**Comment by ufleisch** [comment]
Adding to the points above:

- Use `const` references, objects (especially reference counted ones which detach when not being `const`) and iterators whenever possible
- When you do not have to modify the tags, open the files read-only, see https://github.com/taglib/taglib/issues/1010#issuecomment-841449281.
- You are using Windows. From my experience, file access on Windows is slower than on Linux, especially if a virus scanner is intercepting every file access. So you could make your measurements on a different system or with other virus scanner settings.
- If the presented code is part of a GUI application, a lot of time could be spent by UI updates. I have a project, which uses a similar environment (TagLib, Qt, MingGW on Windows), and for some operations like reading a lot of files, I suspend updates to GUI elements such as `QTreeView` while these operations are performed to speed things up. You could compare its performance with the following procedure
  * Get the Windows version from https://kid3.kde.org/#download
  * Make sure that only TagLib is used by unchecking all other metadata plugins in the settings
  * Drag the folder with your 1464 mp3 files, into Kid3, if the files are in subfolders use "Expand all" from the file list menu
  * Now select all files ("Edit/Select all" or the corresponding shortcut) and measure the time. This will read all tags and all audio properties. Your program should be faster, if it is correctly implemented, because it only reads a subset of the tag frames.

**Comment by MBSadeghzadeh** [comment]
thanks @scotchi. I built it and it was really super fast. 
but I have a problem. 
I want to hash file content but exclude tags and metadata. Reading whole content of files is time consuming. Do you know any method to hash voice files and generate unique keys  very fast?

**Comment by MBSadeghzadeh** [comment]
@scotchi  
Do you know how to do below code with FileRef ?
```

 // BPM
    TagLib::ID3v2::FrameList fl = tag->frameListMap()["TBPM"];
    if(!fl.isEmpty())
        songInfo.bpm = QString::fromLatin1(fl.front()->toString().toCString()).toDouble();
```

**Comment by scotchi** [comment]
> I want to hash file content but exclude tags and metadata. Reading whole content of files is time consuming. Do you know any method to hash audio files and generate unique keys very fast?

It really depends on how accurate you need to be, if your code is IO or CPU bound (I'd guess IO)  I'd guess in most cases if you just did a seek to the 10th second of audio and hashed just that, it'd be accurate enough.  Maybe look at what MusicBrainz does with their acoustic IDs.  But we're pretty clearly getting out of the range of TagLib bugs.  I'd suggest for further discussion on stuff like this to use TagLib's mailing list rather than the bug tracking system.

>  Do you know how to do below code with FileRef ?

`TStringToQString(ref.file()->properties()["BPM"].first()).toDouble();`

**Comment by MBSadeghzadeh** [comment]
> Can you please test with the `tagreader` example from `taglib/examples`? You'll need to build with the CMake option `-DBUILD_EXAMPLES=On`, and want to make sure you're using a release build, not a debug one. Honestly, there are quite a few problems in your code, and it doesn't really make sense to go through them one-by-one here in TagLib's bug tracking, and it'd make more sense to use a stripped down version from our examples directory.
> 
> Also, you're probably not going to get a speedup from using multithreaded code as TagLib is primarily IO, not CPU bound. In fact, I'd expect multi-threaded scanning to be slower, but I haven't done any extensive testing there since the world moved from HDDs to SSDs (multithreaded would definitely be slower with an HDD).
> 
> Once you have `tagreader` built, then you can run something like this:
> 
> `find ~/Music -name \*.mp3 -print0 | time xargs -0 ./tagreader > /dev/null`
> 
> For me that scans all of my 11590 file music collection in about 20 seconds.

I am using MingW. how can I build taglib in release mode? it takes about 24 seconds to load 1464 files?

**Comment by scotchi** [comment]
Again, this question is more appropriate for TagLib's mailing list.  This isn't the place to get tips on C++ development.

**Comment by MBSadeghzadeh** [comment]
thanks @scotchi 
where is TagLib's mailing list?
