### ISSUE TITLE
ID3v2 chapter mark images compatibility issues

### ISSUE THREAD

**Issue by spiderpug** [taglib/taglib#1053]
Hello! 

I'm trying to write MP3 chapter marks with images, but I'm medium successful. 

The tags are written and I can see my two test chapters using `mid3v2`, and OSX Finder also shows them, but only one chapter mark (CH2, without the image) appears in `ffprobe`. After processing the audio file with Auphonic, the first chapter mark is also dropped completely.

`mid3v2 output`:

```
IDv2 tag info for audio.mp3
CHAP=CH1 time=3000..5000 offset=4294967295..4294967295
    TIT2=chapter 1
    APIC=other,  (image/jpeg, 95772 bytes)
CHAP=CH2 time=5000..15000 offset=4294967295..4294967295
CTOC=TOC flags=3 child_element_ids=CH1,CH2
TIT2=test
```

`ffprobe output`:

```
Input #0, mp3, from 'audio.mp3':
  Metadata:
    title           : test
  Duration: 00:00:33.86, start: 0.023021, bitrate: 183 kb/s
    Chapter #0:0: start 5.000000, end 15.000000
    Metadata:
      title           : CH2
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 160 kb/s
    Metadata:
      encoder         : Lavc58.54
```

`taglib framelist output`:

```
ID3v2.3.0, 96939 bytes in tag
TIT2 - "test"
CTOC - "TOC: top level: true, ordered: true, chapters: [ CH1, CH2 ]"
CHAP - "CH1: start time: 3000, end time: 5000, sub-frames: [ TIT2 ]"     # not showing APIC as well ?
CHAP - "CH2: start time: 5000, end time: 15000"

ID3v1
title   - ""
artist  - ""
album   - ""
year    - "0"
comment - ""
track   - "0"
genre   - ""

APE
file does not have a valid APE tag
```

### Example code used

I prepared example code in this repo: https://github.com/taglib/taglib/compare/master...spiderpug:taglib:add-chapter-apic-example

I wonder if there is something that I do wrong or if there is an issue with serializing the APIC embedded frame.

Was also playing with the ruby bindings for taglib, as I'm not proficient in CPP, but similar result.

All input would be appreciated.

**Comment by scotchi** [comment]
I don't personally know the chapters code much (was contributed by a non-regular contributor), but my first inclination would be to try attaching the image frame to the normal tag (i.e. non-embedded) and see if that works to see if the problem is in your frame generation code or in the embedding code.

As a side-note:  you don't need to create the `ByteVector` with `new`.  You can just create it like this:

`ByteVector imgVector;`

**Comment by spiderpug** [comment]
> I don't personally know the chapters code much (was contributed by a non-regular contributor), but my first inclination would be to try attaching the image frame to the normal tag (i.e. non-embedded) and see if that works to see if the problem is in your frame generation code or in the embedding code.

As far as I understand the [ID3 specs](https://id3.org/id3v2-chapters-1.0#Chapter_frame), that would make it unrelated to the chapter mark? In case of a cover image for example, I would not try to use an embedded tag.

> As a side-note: you don't need to create the `ByteVector` with `new`. You can just create it like this:
> 
> `ByteVector imgVector;`

Thank you ;-) I was hacking this together since I was just trying to see if the problem persists when I'm using the CPP lib directly, instead of through ruby. I don't know much about C++, and it seems to show 😄

**Comment by scotchi** [comment]
> > I don't personally know the chapters code much (was contributed by a non-regular contributor), but my first inclination would be to try attaching the image frame to the normal tag (i.e. non-embedded) and see if that works to see if the problem is in your frame generation code or in the embedding code.
> 
> As far as I understand the [ID3 specs](https://id3.org/id3v2-chapters-1.0#Chapter_frame), that would make it unrelated to the chapter mark? In case of a cover image for example, I would not try to use an embedded tag.

Yes, I'm just suggesting that as a way of narrowing down where things are going wrong, not as an actual solution.  If your code works to attach images tags normally, then we can be pretty sure that the problem is somewhere in the chapter code.

**Comment by sbooth** [comment]
I've been attempting to debug the issue and something unusual is definitely going on with the attached picture frame. The size of the embedded APIC frame is too large (the size meaning the 4 bytes following 'APIC' in the rendered ID3v2 tag).

This is reason that framelist doesn't see the APIC; the size is causing a null return in [id3v2framefactory.cpp](https://github.com/taglib/taglib/blob/0470c2894d07523af11f1ac4e2fa7ce85ced26fe/taglib/mpeg/id3v2/id3v2framefactory.cpp#L150). Specifically the check `header->frameSize() > data.size()` is failing.

I tried replacing the embedded APIC with an embedded TIT3 to see if the issue is specific to APIC or general for the second embedded frame and the TIT3 worked correctly.

**Comment by spiderpug** [comment]
> I've been attempting to debug the issue and something unusual is definitely going on with the attached picture frame. The size of the embedded APIC frame is too large (the size meaning the 4 bytes following 'APIC' in the rendered ID3v2 tag).
> 
> This is reason that framelist doesn't see the APIC; the size is causing a null return in [id3v2framefactory.cpp](https://github.com/taglib/taglib/blob/0470c2894d07523af11f1ac4e2fa7ce85ced26fe/taglib/mpeg/id3v2/id3v2framefactory.cpp#L150). Specifically the check `header->frameSize() > data.size()` is failing.
> 
> I tried replacing the embedded APIC with an embedded TIT3 to see if the issue is specific to APIC or general for the second embedded frame and the TIT3 worked correctly.

Thanks @sbooth for debugging this. I also had my hex editor open and noticed some issues with the frame size, when the payload is bigger than ~110 bytes. At some points the 4 byte size jump to 256, even though the fake image I provided was 114 bytes. I think it also depends on the amount of data other embedded frames provide.

**Comment by sbooth** [comment]
After looking into this further I believe the problem is not on the write side but on the read side.

It appears that the CHAP frame is rendered as version 3 and the embedded frames are rendered as version 4. 

When the embedded frames are read (in `ChapterFrame::parseFields`), they are forced to the version of the [CHAP frame](https://github.com/taglib/taglib/blob/0470c2894d07523af11f1ac4e2fa7ce85ced26fe/taglib/mpeg/id3v2/frames/chapterframe.cpp#L270). In this case, the size of the APIC frame in version 4 is a sync-safe integer and in version 3 it is not, leading to the size discrepancy when the sync-safe value is read as a non-sync safe value. The end result is that `FrameFactory::instance()->createFrame()` returns null and the APIC frame isn't parsed. I assume any version 4 frame would have the same issue.

**Comment by sbooth** [comment]
I'm not sure why the ID3v2 version isn't propagating to the embedded frames, but a workaround is to change your program to use ID3v2.4.

**Comment by sbooth** [comment]
Something similar to this change should fix the problem:

```diff
--- a/taglib/mpeg/id3v2/frames/chapterframe.cpp
+++ b/taglib/mpeg/id3v2/frames/chapterframe.cpp
@@ -294,8 +294,10 @@ ByteVector ChapterFrame::renderFields() const
   data.append(ByteVector::fromUInt(d->startOffset, true));
   data.append(ByteVector::fromUInt(d->endOffset, true));
   FrameList l = d->embeddedFrameList;
-  for(FrameList::ConstIterator it = l.begin(); it != l.end(); ++it)
+  for(FrameList::ConstIterator it = l.begin(); it != l.end(); ++it) {
+    (*it)->header()->setVersion(header()->version());
     data.append((*it)->render());
+  }
 
   return data;
 }
```

However, this requires making `ChapterFrame` a friend of `Frame`.  Perhaps @scotchi has a more elegant solution.

**Comment by ufleisch** [comment]
I had a look at the fix from @sbooth and I think it solves the problem. When adding an APIC frame to a CHAP frame in an ID3v2.3.0 tag with the unpatched version, it has a synchsafe integer for the size, which is not supported in ID3v2.3.0. With the patch, a correct APIC frame for ID3v2.3.0 without synchsafe integer is added.

`ffprobe` will show all chapters for an ID3v2.3.0 tag written with the patched version (however it only displays a "title", it seems to ignore APIC and COMM frames which I added to the CHAP frame). It seems that `ffprobe` has problems with APIC frames with synchsafe integers, if I have such a correct frame in a CHAP frame, it is ignored by `ffprobe`, so CHAP frames in ID3v2.4.0 tags seem to be only accepted by `ffprobe` if they do not contain APIC frames.

The same problem seems to exist with other software using FFmpeg. `mpv` can jump to chapters when the **Page Up**/**Page Down** keys are pressed, but this works only for those chapters which are also displayed by `ffprobe` (i.e. CHAPs without APIC or ID3v2.3.0 CHAPs with APICs written by the patched version), so I suppose that it is using FFmpeg. Tagging software such as `mid3v2` from mutagen and `kid3` (which uses TagLib) accept all variants of CHAP and TOC frames written by TagLib.

I also tested the VLC 3.0 dev nightly snapshot for Windows, it seems to support MP3 chapters in its Playback/Chapters menu, but the chapter names seem to contain a bit of garbage, for example "chapter 1APIC" for a CHAP frame with title "chapter 1" and followed by an APIC frame, probably this is not correctly parsed. On Android, I found an app "Voice" on F-Droid, which seems to support all variants of CHAP frames. But I could not find a software which displayed pictures for the chapters, is there such a software and could you use it with files written by TagLib?
