### ISSUE TITLE
Link error in TagUnion

### ISSUE THREAD

**Issue by hananoki** [taglib/taglib#1057]
About taglib/taglib/tagunion.h

It looks like this now
`class TagUnion : public Tag`

I think the TAGLIB_EXPORT designation is missing
`class TAGLIB_EXPORT TagUnion : public Tag`

It's my first time posting, so sorry if I'm being rude.

**Comment by ufleisch** [comment]
I do not think that this is necessary since `TagUnion` is only used internally and not part of the public API. Could you please describe your issue with a bit more details:

- What operating system and compiler are you using?
- Static or dynamic library?
- Which version of TagLib (e.g. 1.12 or git master)?
- If you built TagLib yourself, provide instructions how it was built, e.g. the CMake and make commands.
- When the issue is reproducible, please provide detailed instructions how to reproduce it.
- If you report a "link error", I would at least expect an error message from the linker.

As the problem seems to be about exporting of symbols, I assume that you are using Microsoft Visual C++ on Windows. I tested the current master branch with MSVC on Windows 10, both built as a static and a dynamic library and I did not see any issues, `tagreader.exe` worked correctly and all tests passed, so I do not think that there is any link error on Windows.

**Comment by hananoki** [comment]
Windows10 MSVC2022, TagLIb was improved based on 1.12, and the project file for Windows was created manually.
(I don't use `make` or `CMake`)
I have placed the modified version in [my repository](https://github.com/hananoki/TagLib-for-Windows).

The problem occurs when using it as a dynamic library.
I believe the problem can be reproduced with the following code.

```c++
TagLib::FileRef f( L"test.mp3" );
auto* tag = f.tag();  //< The type returned here is TagUnion
auto* tag_union = (TagLib::TagUnion*) tag;
auto* mp3v2 = (TagLib::ID3v2::Tag*) tag_union->tag( 0 ); //< link error here
```

> I do not think that this is necessary since TagUnion is only used internally and not part of the public API. 

Since the return value is a `TagUnion`, I don't think it can be handled without being exported.
Am I wrong?

![taguni](https://user-images.githubusercontent.com/37146228/185912520-507cba0b-4fe2-44f6-88a3-fa194259911b.png)

**Comment by jonaski** [comment]
Why are you using `TagUnion` and not `Tag` directly? What's with C-casts?
ie.: `TagLib::Tag *tag = fileref->tag();`

**Comment by hananoki** [comment]
This is exactly what I wanted to do.
I thought `ID3v2` could only be obtained via `tags()`.

I also learned from the `FileRef` reference that my operation was a mistake.
I appreciate your response, thank you.
