### ISSUE TITLE
Wrong library install name on macOS

### ISSUE THREAD

**Issue by ryandesign** [taglib/taglib#1065]
In taglib 1.13 the library install name is wrong on macOS (it isn't an absolute path like it needs to be):

```sh
$ port installed taglib && otool -L /opt/local/lib/libtag.dylib | head -n2
The following ports are currently installed:
  taglib @1.13_0 (active)
/opt/local/lib/libtag.dylib:
	lib/libtag.1.dylib (compatibility version 1.0.0, current version 1.19.0)
```

It was correct in taglib 1.12:

```sh
$ port installed taglib && otool -L /opt/local/lib/libtag.dylib | head -n2
The following ports are currently installed:
  taglib @1.12_0 (active)
/opt/local/lib/libtag.dylib:
	/opt/local/lib/libtag.1.dylib (compatibility version 1.0.0, current version 1.18.0)
```

I suspect 507a42871c7b1226bd23c3b26260afe5b3861fed introduced this regression.

**Comment by ufleisch** [comment]
Sorry for the trouble, there have been some contributions improving the build system and making it more standard. As I am having `brew` on my Mac, I could not reproduce the issue exactly, but I built and installed TagLib 1.13 using the CMake definitions from [your port](https://github.com/macports/macports-ports/blob/master/audio/taglib/Portfile). To get an absolute install name, I just had to add `-DCMAKE_INSTALL_LIBDIR=/opt/local/lib` to the CMake definitions (maybe this would be `-DCMAKE_INSTALL_LIBDIR=${destroot}${prefix}/lib` in the Portfile).

Looking at your Portfile, I have the following remarks:

- `WITH_ASF` and `WITH_MP4` do not exist anymore
- Use `BUILD_TESTING` instead of `BUILD_TESTS`
- Tests now work with shared libraries, so there is no need to switch `BUILD_SHARED_LIBS` off for the tests.

**Comment by ryandesign** [comment]
No worries and thanks for the suggestions.

Yes I could override `CMAKE_INSTALL_LIBDIR` but I shouldn't have to. 😄 And including the destroot path within the install name would not be correct. The install name must be the absolute path where the library will ultimately end up, not the temporary staging area that a package manager might set destroot to.

Fortunately GNUInstallDirs has separate absolute-path variables one can use (`CMAKE_INSTALL_FULL_LIBDIR` instead of `CMAKE_INSTALL_LIBDIR`) which fixes the problem. I've sent a PR.
