### ISSUE TITLE
Can not detect audio property and tag for a few M4A file format

### ISSUE THREAD

**Issue by nathnaeld** [taglib/taglib#1077]
I was working on parsing M4A files. TagLib works well on almost all but it fails on a few M4A files. It does not consider them valid files. I have attached a sample audio.

[audio.zip](https://github.com/taglib/taglib/files/10472790/audio.zip)

**Comment by ufleisch** [comment]
I cannot see a problem with the file *[12] In Real Life.m4a* in the attached archive.

**Comment by 40th** [comment]
Looks like some sort of atom problem.  Pic should be a start (.length == 0).

![atom heart](https://40th.com/gfx/gh/one_too_many.png)

**Comment by ufleisch** [comment]
Thanks for the additional information. I now think that I can figure out why you see a problem and I do not. If I look at the same place (_mp4file.cpp_, l. 39pp)  with your example file in the debugger, I see `length=3342441612` whereas you see `length=0`. The reason is that I am on Linux (amd64 architecture) where `long` (the type of `length`) has 64 bits whereas on Windows (I suppose you are on Windows) it has only 32 bits. The length of 3342441612 is too large for a signed 32 value (`INT_MAX` is 2147483647).
Unfortunately, changing the type of `length` to a 64-bit value would break binary compatibility, so we cannot do this for TagLib 1.x, we can do this when we start working on TagLib 2.x where we can break binary compatibility. There are a lot of other places which are affected by `long` having only 32 bits on Windows. For my project [Kid3](https://kid3.kde.org), I have patched TagLib for the Windows version, see [taglib-1.13-win00-large_file.patch](https://invent.kde.org/multimedia/kid3/-/blob/master/packaging/patches/taglib-1.13-win00-large_file.patch), so if you are building TagLib yourself, you could apply this patch too.

**Comment by 40th** [comment]
So we now agree on the value of the length, but why does a 2:57 AAC track have a length of 3,342,441,612 for anything?

![atom heart](https://40th.com/gfx/gh/one_too_many_2.png)

**Comment by ufleisch** [comment]
I agree that more should be checked. The last "header" `c7 39 9c 8c 92 78 b1 f9` is obviously garbage, so that file should be detected as invalid. Probably these header bytes alone should be enough to `setValid(false)`, I will try to find a specification which contains information about valid length and atom name values.

**Comment by 40th** [comment]
> I would suggest that we mark such files as invalid.

Invalid is not the only problem, though.  An -incorrect- size for an atom is just as bad.  And that is the problem with the .m4a file, here (at top).  The length is not invalid (2794 bytes), and it only just so happens that the 4-byte size of the next atom is grossly wrong (3,342,441,612 bytes); those 4 bytes could have been, as you determine here,  a valid size (less than the file's size).

Look at any 4 bytes of an AAC bitstream to see what the size could have been.  For example, I see 00 1f ac cc bytes in there, and that's only 2,075,852 bytes, which is smaller than the 7,162,072-byte m4a file, so your test would not detect this (no less damaging than the 3 billion one since either will overwrite the true mdat start).  The  c7 39 9c 8c just happens to be absurdly impossible.


Not too important: Nothing says mdat has to be at the end (but it almost always is when it comes to files of known length -- i.e., when not an active, unknown-when-it-will-end recording), but it won't hurt to verify that the mdat atom is present.  In the example bad file in this topic, it is not present.

**Comment by ufleisch** [comment]
We could also check if the following four bytes (the name or type) are only printable ASCII characters or 251 (the copyright sign © in ISO-8859-1), this should sort out a lot of non-atoms. I did not find any specification about what characters can be in the name, but this is what I have seen in the wild.
