### ISSUE TITLE
Supporting get pictures of flac?

### ISSUE THREAD

**Issue by Kyant0** [taglib/taglib#1161]
We can get the pictures via `tag->complexProperties("PICTURE")`, but it seems the pictures in `flacFile->pictureList()` are not included in the `complexProperties`. Why not unify the flac pictures api? I have to workaround with the flac case.

My code:
```cpp
    const char *file_path = env->GetStringUTFChars(path, nullptr);
    TagLib::FileRef fileRef(file_path, false);
    env->ReleaseStringUTFChars(path, file_path);

    auto flacFile = dynamic_cast<TagLib::FLAC::File *>(fileRef.file());
    if (flacFile != nullptr && flacFile->isValid()) {
        auto pictureList = flacFile->pictureList();
        if (!pictureList.isEmpty()) {
            TagLib::ByteVector picture = pictureList.front()->data();
            if (picture.isEmpty()) {
                return nullptr;
            }
            jbyteArray bytes = env->NewByteArray(static_cast<jint>(picture.size()));
            env->SetByteArrayRegion(
                    bytes,
                    0,
                    static_cast<jint>(picture.size()),
                    reinterpret_cast<const jbyte *>(picture.data())
            );
            return bytes;
        }
    }

    auto tag = fileRef.tag();
    if (tag == nullptr) {
        return nullptr;
    }
    auto pictures = tag->complexProperties("PICTURE");
    if (pictures.isEmpty()) {
        return nullptr;
    }
    TagLib::ByteVector picture = pictures.front().value("data").toByteVector();
    if (picture.isEmpty()) {
        return nullptr;
    }
    jbyteArray bytes = env->NewByteArray(static_cast<jint>(picture.size()));
    env->SetByteArrayRegion(
            bytes,
            0,
            static_cast<jint>(picture.size()),
            reinterpret_cast<const jbyte *>(picture.data())
    );
    return bytes;
```

**Comment by ufleisch** [comment]
The problem is that FLAC files have a `XiphComment` tag, but the picture is not in the Vorbis Comments, but in a separate `METADATA_BLOCK_PICTURE`, which thus cannot be accessed via the `tag()`, but via the `file()`. So you just have to go via the `file()` for all formats and you can access pictures in a unified way for all file types.

You can have a look at [examples/tagreader.cpp](https://github.com/taglib/taglib/blob/master/examples/tagreader.cpp) and [examples/tagwriter.cpp](https://github.com/taglib/taglib/blob/master/examples/tagwriter.cpp), they go via `file()`. You can verify with these two examples that pictures can be read and written for all supported formats.

**Comment by Kyant0** [comment]
I see. Thanks a lot.
