### ISSUE TITLE
Clarify news

### ISSUE THREAD

**Issue by lazka** [taglib/taglib#1214]
The 2.0 news state that `New major version, binary incompatible, but source-compatible with the latest 1.x release if no deprecated features are used.`.

But for Windows various function signature types have changed in an incompatible way, for example in ca8c2e07ecae6c8c5bb1c47a1f11

**Comment by scotchi** [comment]
You're saying that switching from `long` to `offset_t` caused your project not to compile anymore?

**Comment by lazka** [comment]
VLC doesn't at least: https://code.videolan.org/videolan/vlc/-/issues/28502

**Comment by scotchi** [comment]
Do you have other examples?  The things used there have been marked as deprecated for many years, and the changelog specifically says that deprecated features have been removed.

**Comment by scotchi** [comment]
And I don't believe that converting `offset_t` to `long` should cause an error unless `-Werror` is enabled on the project, turning warnings into errors, which isn't really an issue of source compatibility but more a project's choice of compiler flags.

**Comment by ufleisch** [comment]
Probably, I should clarify the "source compatible" from the [news](https://github.com/taglib/taglib/blob/master/CHANGELOG.md) to the wording in the [announcement](https://mail.kde.org/pipermail/taglib-devel/2024-January/003075.html) "mostly source compatible, therefore simple applications should build without changes, and it should be possible to migrate more complex applications without bad surprises, i.e. the compiler errors and the CHANGELOG.md should provide enough information". Since method signatures have changed, you will have to adapt client source code if it extends classes from TagLib, e.g. `File`, `IOStream`, `StringHandler`, or `FrameFactory`. Simple code has a chance to build without changes. The guys from Arch Linux managed to patch all their applications which depend on TagLib in a single day, as can be seen in the [Rebuild Todo List taglib 2.0](https://archlinux.org/todo/taglib-20/), this list also contains [vlc](https://archlinux.org/packages/extra/x86_64/vlc/), so you can follow the link to the package details, then [View Changes](https://gitlab.archlinux.org/archlinux/packaging/packages/vlc/-/commits/main), which leads you to the commit with the changes for TagLib 2.0. For VLC, it seems that the changes include mostly deprecated functions which had to be adapted.

**Comment by lazka** [comment]
> **UPDATE**: I saw from the link provided above that you know the Arch Linux patch. But the `FileName` class has not changed since 11 years, so I wonder if this ever compiled for Windows...

We are building VLC and taglib for many years now, so it somehow is working :)
My C++ skills are lacking, but I guess this https://github.com/taglib/taglib/commit/322085f90e328dd588c967f9623d3cd5faf8892a Why that's not an issue on Arch, I don't know.

The other changes are likely not an issue for Arch since long and size_t are the same size on Linux, but not on Windows.

Anyway, all those taglib changes sound like a good idea and are welcome, I was just a bit surprised when I rebuilt packages motivated by the news entry and hit those roadblocks :)

Feel free to close this.

**Comment by ufleisch** [comment]
Sorry, you are right, I just `git blame`d the code, and this did not show the lines I removed earlier. I have updated the [CHANGELOG.md](https://github.com/taglib/taglib/blob/master/CHANGELOG.md) to clarify that it may need a bit more work to migrate. I also noticed, that when compiling for Windows, the change of the file offsets from 32 to 64 bits causes additional adaptions, but without them, large files would not be supported on Windows.

**Comment by lazka** [comment]
Just a short followup, VLC master updated to taglib 2 and backporting those fixes (https://github.com/msys2/MINGW-packages/blob/c2510aad3e0885c3e66af0f768690bd0fc6c0d8a/mingw-w64-vlc/PKGBUILD#L147-L152) allowed us to update taglib now: https://github.com/msys2/MINGW-packages/pull/20034#1219
