### ISSUE TITLE
I'm having trouble installing taglib in Windows

### ISSUE THREAD

**Issue by silincone** [taglib/taglib#1252]
As I have mentioned above, I am not able to install taglib in Windows 11. 

I saw the INSTALL.md file and ran these below commands in the command prompt.
`$env:TAGLIB_SRC_DIR = "${env:HOMEDRIVE}${env:HOMEPATH}/projects/taglib/src/taglib" $env:TAGLIB_DST_DIR = "${env:HOMEDRIVE}${env:HOMEPATH}/projects/taglib/src/msvs_vcpkg_build" cd $env:TAGLIB_SRC_DIR`
It fails at the third command. It says that so such directory exists.

What am I doing wrong here?

As far as I know, taglib source code doesn't provide the directory "src/".

I tried to install/build myself.
I created a new folder "build" in the root of taglib source code. 
I saw that in CMakeLists.txt, it searches for utf8cpp dependency in the directory "3rdparty/". So I copied the source code of utf8cpp from github and pasted it there.
I finally ran the following command inside the "build" directory.
`cmake ../ -DCMAKE_BUILD_TYPE=Release -DWITH_ZLIB=OFF`
And I am stuck here, what do I do next?!

As you can see, I am really bad at this, so please, let me know what to do in detail. 
Thank you!

**Comment by ufleisch** [comment]
On the line above `$env:TAGLIB_SRC_DIR = "${env:HOMEDRIVE}${env:HOMEPATH}/projects/taglib/src/taglib"` it is written

    # Adapt these environment variables to your directories

and this is what you should do. Set the first variable to the path where you have the TagLib sources, and the second where you want to build it.

Concerning `utf8cpp`: A few lines above, I have suggested that you install the dependencies with `vcpkg`. If you do this, the `cmake` option `-DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"` suggested in _INSTALL.md_ will make sure that `cmake` will find `utf8cpp` and all other dependencies. If you have installed it without `vcpkg` in another place, you will not have such a `vcpkg` toolchain file and you should use `CMAKE_INSTALL_PREFIX ` (or alternatives
like  `CMAKE_PREFIX_PATH`, `CMAKE_SYSTEM_PREFIX_PATH`) so that `cmake` can find them. If you have fetched the TagLib sources using `git clone` you have another possibility for `utf8cpp`, you can use `git submodule update --init`  to fetch its source with Git (as it is described in the error message).

**Comment by silincone** [comment]
I did as you said and I built the project using MSVC. 

I tried to compile this code snippet 
```
TagLib::FileRef f("path/to/music.mp3");

 
f.tag()->setAlbum("Artist Name");
f.save();
```

But it failed and gave me 8 errors. All of which are LNK2019

![Screenshot 2024-11-12 122045](https://github.com/user-attachments/assets/881d22c6-e88b-4e6a-85f6-2a947f8cfd8d)

Please help me out.

**Comment by ufleisch** [comment]
I built TagLib exactly as described in _INSTALL.md_, including running the unit tests successfully, until the line after "# Install to \pkg folder on current drive" where it is installed. I then copied the resulting pkg folder to a new project folder and renamed it to TagLib, just to mimic your configuration. I then took your _CMakeLists.txt_, adapted it slightly, took your code, enclosed it into a `main` function and compiled the whole thing using

    cmake -B build -G "Visual Studio 17 2022"
    cmake --build build --config Release

Then I set the `PATH` to include _taglib.dll_ and _zlib.dll_ and finally run the executable successfully

    .\build\Release\CMakeProject1.exe

However, I have doubts, if you really built your TagLib exactly as described because my package does *not* contain a _share_ folder, and it compiled without problems. The output of your screenshot looks like you try to link to a dynamic library but provide a static library. My _TagLib_ folder looks like this:

```
├───bin
│       framelist.exe
│       strip-id3v1.exe
│       tag.dll
│       taglib-config.cmd
│       tagreader.exe
│       tagreader_c.exe
│       tagwriter.exe
│       tag_c.dll
│
├───include
│   └───taglib
│           aifffile.h
│           (... many header files ...)
│           xmproperties.h
│
└───lib
    │   tag.lib
    │   tag_c.lib
    │
    ├───cmake
    │   └───taglib
    │           taglib-config-version.cmake
    │           taglib-config.cmake
    │           taglib-targets-release.cmake
    │           taglib-targets.cmake
    │
    └───pkgconfig
            taglib.pc
            taglib_c.pc
```

By the way: You do not need the "I tried to do something" line, the library is already given in the line above.

**Comment by jonaski** [comment]
Make sure you are not mixing Release and Debug builds, did you also build your project in Release?

**Comment by ufleisch** [comment]
> (I did not install cppunit as it was optional)
> I ran this command: cmake --build $env:TAGLIB_DST_DIR --config Release --target check
> It gave me an error

`--target check` means running the unit tests, which will not work if cppunit is not installed. The preceeding `cmake` command in _INSTALL.md_ is enough to build the library. I personally feel more confident if I see that the unit tests are passing.

> Does this mean that even though I am using static library, I must still link the .dll files?

No, I thought that you were using the first example command, which generates dynamic libraries, but if you are using static libraries (which probably saves you much trouble), it is not needed to extend the `PATH` to DLLs. As you can see, the `target --check` example command in the static case does not have anything added to the `PATH`. For the static library, you can start from the line `# Static library`.

During development, it is probably a good idea to build everything with `--config Debug`.

**Comment by silincone** [comment]
I successfully built the static release but when it came to testing the built debug, i. e.,
 `cmake --build $env:TAGLIB_DST_DIR --config Debug --target check`
I got an error.

![image](https://github.com/user-attachments/assets/d0dd1a7a-397e-4c6b-a21e-3b8cf95c52f1)

Here are the commands that I ran: 
```
cmake -B $env:TAGLIB_DST_DIR -DBUILD_SHARED_LIBS=OFF -DVISIBILITY_HIDDEN=ON `
  -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DBUILD_BINDINGS=ON `
  -DCMAKE_BUILD_TYPE=Debug `
  -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
  -G "Visual Studio 17 2022"
```

`cmake --build $env:TAGLIB_DST_DIR --config Debug`

`cmake --build $env:TAGLIB_DST_DIR --config Debug --target check` <-- Here's where I got the error.

So, I thought maybe I should change the first command to this:
```
cmake -B $env:TAGLIB_DST_DIR -DBUILD_SHARED_LIBS=OFF -DVISIBILITY_HIDDEN=ON `
  -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DBUILD_BINDINGS=ON `
  -DCMAKE_BUILD_TYPE=Release `  <--------------------------------------------------------- Here is the change.
  -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
  -G "Visual Studio 17 2022"
```
Then I continued with the rest of the commands, and I still got that error.

Here is the LastTest.log contents:

```
Start testing: Nov 15 16:14 India Standard Time
----------------------------------------------------------
1/1 Testing: test_runner
1/1 Test: test_runner
Command: "C:/dev/taglib-2.0.2/build/Debug/tests/Debug/test_runner.exe"
Directory: C:/dev/taglib-2.0.2/build/Debug/tests
"test_runner" start time: Nov 15 16:14 India Standard Time
Output:
----------------------------------------------------------
<end of output>
Test time =   0.14 sec
----------------------------------------------------------
Test Failed.
"test_runner" end time: Nov 15 16:14 India Standard Time
"test_runner" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Nov 15 16:14 India Standard Time

```

Please tell me what I am doing wrong. And also, should I set `DCMAKE_BUILD_TYPE` to `Debug` for building Debug binaries?

**Comment by ufleisch** [comment]
When running the commands from _INSTALL.md_ after `# Static library`, all tests are passing, so I have no problems. The example uses a release build. Since I don't use Windows by choice and am actually always on Linux, this bug tracker is probably not the right place for basic Windows support.
