### ISSUE TITLE
Add support for VBRI headers (as an alternative to Xing headers)

### ISSUE THREAD

**Issue by gonemad** [taglib/taglib#136]
Some mp3 files do not have a Xing header, but have a VBRI header instead.  This should be read so a correct bitrate and length can be calculated

http://www.codeproject.com/Articles/8295/MPEG-Audio-Frame-Header#VBRIHeader

**Comment by TsudaKageyu** [comment]
I'm thinking of supporting VBRI headers as a continuation of #506.
Implementation will be easy, but I don't have an actual MP3 file with a VBRI header or an encoder can produce such files. Could somebody provide us with a sample file?

**Comment by lalinsky** [comment]
You can use this:

https://bytebucket.org/lazka/mutagen/raw/82f655678300cdffdc61fdbb1c6482f16c2f098c/tests/data/vbri.mp3
https://bitbucket.org/lazka/mutagen/src/82f655678300cdffdc61fdbb1c6482f16c2f098c/mutagen/mp3.py?at=default#cl-215

(Mutagen has a different license than TagLib, but the code was written by me, so that's fine.)

**Comment by TsudaKageyu** [comment]
Thanks! I'll do it soon.

**Comment by TsudaKageyu** [comment]
This feature is already included in #506.
