### ISSUE TITLE
Dead stores in some of the code

### ISSUE THREAD

**Issue by DidierMalenfant** [taglib/taglib#459]
Code analysis in Xcode picks up a few dead stores in the code:

taglib/flac/flacfile.cpp:218:5: Value stored to 'foundVorbisCommentBlock' is never read
taglib/mod/modfile.cpp:170:22: Value stored to 'fineTune' is never read
taglib/mod/modfile.cpp:173:21: Value stored to 'volume' is never read
taglib/mpc/mpcproperties.cpp:211:7: Value stored to 'pos' is never read
taglib/taglib/ogg/opus/opusproperties.cpp:145:3: Value stored to 'pos' is never read

These should probably be fixed but it seems in some cases that the value is incremented to point to the next block of data, but this is never used.

I don't want to just delete the line in case the increment value is...well...valuable but we should at least change this into comments for the time being.

Thoughts?

**Comment by scotchi** [comment]
I started going through this one annotating the issues, but decided after making the changes not to commit them.

At present, it just catches a few things, and they're all intentional, and they're easy to scan manually when looking over the code.  The changes to silence the warnings make the code worse, so I don't think it's worth it.
