### ISSUE TITLE
ID3v2 Chapter frame constructor should take a String

### ISSUE THREAD

**Issue by EvilSquirrel** [taglib/taglib#514]
The spec clearly states that the Element ID property of a chapter frame is a null-terminated text string, but the ChapterFrame constructor starts with `ChapterFrame(const ByteVector &eID, ...`
This forces calling code to look like this:
``` c++
new ChapterFrame(String("test").append(char(0)).data(TagLib::String::Latin1), ...
```
instead of this:
``` c++
new ChapterFrame(String("test"), ...
```

**Comment by EvilSquirrel** [comment]
Given that the spec states the element ID is a null-terminated string, any reason why the parameter cannot be a String?

**Comment by sbooth** [comment]
The spec is here: http://id3.org/id3v2-chapters-1.0

I agree with @EvilSquirrel that it makes sense to add a constructor that takes a string. I'm less sure on whether and how the existing `ByteVector` constructor should change.  The class itself is a little strange because the constructor doesn't add a null byte but `setElementID()` does, and on rendering no null is added.  I think the behavior should probably be made consistent across various inputs.

**Comment by FestusHagen** [comment]
I agree, A String constructor is appropriate, however the `ByteVector` constructor still needs the termination of `ElementID` validated as well as a few other places where `ElementID` is created. (Not sure where else at this moment)

I'll close my half baked fix.

**Comment by scotchi** [comment]
After re-reading the spec, ByteVector is actually the correct type here.  It repeatedly says "String", but that word isn't used the same way that it is in the rest of the ID3v2 spec -- it's specifically used as a (ASCII) identifier in the same way that frame IDs are.  I'll add something to add additional padding if it isn't present that keeps current code working.
