### ISSUE TITLE
FileRef: Using IOStream instead of a file name 

### ISSUE THREAD

**Issue by chouquette** [taglib/taglib#526]
Hi,

I'm trying to add taglib support for VLC on WinRT, which has a few "fun" limitations with regards to file.
Basically, we can't fopen the file, which obviously lead to TagLib's parsing failure.

One way to fix this would be to feed taglib using the IOStream interface, which is fairly trivial. The issue lies in using this IOStream afterward. The FileRef class doesn't provide a method for this. So far the ways I see are:
- To not use FileRef, and reimplement the file extension factory somewhere else, which also drops the ability to use potential FileTypeResolver 
- Extend the FileRef class with a create method that takes an IOStream*, however, in order to use FileTypeResolver with an IOStream, we need to add another method to the interface, which would (most likely) break the ABI. I assume this to be a problem :)
- Extend the FileRef class but not expose FileTypeResolver for files accessed through IOStream

I'd be happy to provide a pull request, though I'd appreciate any insight/advices on how to achieve this!

Thanks in advance,

**Comment by lalinsky** [comment]
Well, the only added value of `FileRef` and `FileTypeResolver` is filename-based type guessing. A `IOStream` subclass still needs to return some kind of filename. So my suggestion would be to add another constructor to `FileRef` that accepts a `IOStream` pointer and uses `stream->filename()` to find the right type.

**Comment by chouquette** [comment]
Wouldn't that be an issue with regard to the part of FileRef::create() using FileTypeResolver ? (point 2 above)

**Comment by lalinsky** [comment]
Ah, I knew I'm forgetting something. You are right, we can't add a new virtual method there. Well, for now we can probably just not use `FileTypeResolver` in `master` and add only support for that in the `taglib2` branch.

**Comment by chouquette** [comment]
That's fine by me. I'll try to propose something this week.
Thanks for your answers!

**Comment by scotchi** [comment]
Sorry to have jerked you around a bit here, but after reading through this, I'm not sure that I agree with Lucas that this patch makes sense.  It feels like a lot of extra code to support a special case in one project.  I'm not convinced that it makes sense to support using a FileRef in cases where the file can't be opened.

If the block of code that would need to be copied into your project were ginormous or especially tricky, it'd make sense to me, but at present, it's basically just a map from extensions to namespaces.  (Which honestly, shouldn't generally be used in major applications anyway since you'd want to do mime type detection.)

What feels like it *might* make more sense would be dumping the mapping into a configuration file of some sort ("taglib-handlers.xml" or something) and then writing a tiny generator which basically generates the `create()` function.  That generator could be modified and reused in other projects if really needed.  (And this would have the benefit of also probably making TagLib's code cleaner.)

**Comment by TsudaKageyu** [comment]
Your commit has been merged. Thanks.
