### ISSUE TITLE
Multiple Xiph comments in a FLAC file

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#576]
If a FLAC file has multiple Xiph comments, TagLib only reads the first one. However, it overwrites all Xiph comments with the same contents.
I wonder if it is a consistent way of handling multiple tags. MPEG, AIFF or WAV can also have duplicate tags, and they just ignore duplicate ones. I think we should leave duplicate tags untouched as for FLAC files too.

**Comment by gogglesguy** [comment]
According to the FLAC format: "There may be only one VORBIS_COMMENT block in a stream". 

Keeping multiple xiph comments in a stream could result in unpredictable behaviour. If you update the xiphcomments using taglib, but a third party client may read a different xiph comment block (or vice versa). I don't think the MPEG,AIFF, WAV method is necessary the best way to go. I think we should remove redundant vorbiscomment blocks and keep the first one found (most likely the one read by other software).

**Comment by sbooth** [comment]
I agree with @gogglesguy that FLAC files with more than one vorbis comment block should be handled as noncompliant.  TagLib definitely shouldn't write noncompliant files; I think the best course of action is to coalesce the multiple blocks into one to avoid data loss.

**Comment by TsudaKageyu** [comment]
I agree with @sbooth that we should stick to the specifications. However...

As for FLAC, the specfication clearly states that VORBIS_COMMENT cannot be redundant. So removing redundant tags would be compliant. However, the specifications of MPEG, AIFF or WAV don't mention ID3v2 tags and the specification of ID3v2 doesn't clarify how a tag should be stored in each audio file as far as I know.

**Comment by scotchi** [comment]
I think there are times where we don't have to have something spelled out in the spec to decide what's reasonable and unreasonable behavior.  In the particular case of multiple ID3v2 tags in the same file, I personally think it's pretty clear that those are created by buggy software and should be treated as such.

Dumping ID3v2 into AIFF and WAV is a bit of a weird thing to do, but for AIFF I just copied what Apple does since it's an Apple format.  I found some other software that was doing that for WAV and decided to copy the behavior there as well.  If we were to find multiple tags in multiple differently named RIFF chunks, then I think the issue of merging them could be relevant, but is that actually something we've seen in the wild enough to bother worrying about it?  Unless we're actually seeing something like this happen more than in some extremely rare cases, I'd say it's safe enough to just throw out the second tag.

**Comment by gogglesguy** [comment]
Yes, what @scotchi says, is this actually a real world problem?

**Comment by TsudaKageyu** [comment]
#450 is a good example of real world problem.
I have actually seen MP3 and WAV files that have duplicate tags, but not FLAC and AIFF. I just pointed out about TagLib's behavior.

As for MP3, I know the combination of Exact Audio Copy and LAME creates such files when configured incorrectly. Though I'm not sure what software creates such WAV files, I believe they are created definitely buggy software.

**Comment by TsudaKageyu** [comment]
Additionally, before #492, TagLib used to read the last tag and overwrite the first one on AIFF and WAV...
