### ISSUE TITLE
Genre tag at ID3 v2.3

### ISSUE THREAD

**Issue by PSlava** [taglib/taglib#631]
Source file with id3 v2.3 tag and genre tag (TCON frame) written as "(3)". TagLib reads it and replaces by number "3". On save genre tag will be stored as "3". But it's not write. Because according ID3 v2.3 specification ID3V1 genre tag should be stored as "(3)" ( http://id3.org/id3v2.3.0 ).
Saving genre index without parentheses is valid for 2.4, but not for 2.3.

**Comment by CyberSinh** [comment]
This non respect of the ID3v2.3 standard makes the reading of the "genre" tag very little user friendly with Windows, even in the latest version. Indeed, in the file explorer, Windows displays only the genre number. Do the maintainers of Taglib consider correcting this issue in a future version? Thank you for your help.

**Comment by scotchi** [comment]
Are you using a very old version of TagLib by any chance?  I remember this being fixed a long time back and from a quick look in the code, the fix seems to be there in the last several versions of TagLib.

**Comment by scotchi** [comment]
(Obviously if it were written with an old version of TagLib, it wouldn't be fixed unless you rewrote the tag correctly with a newer version...)

**Comment by CyberSinh** [comment]
I tested with the last commit of the master branch and the problem seems to be still there.

**Comment by scotchi** [comment]
I just tried it with a very slightly modified `tagwriter`:

    Leonard: /Users/scott/Projects/taglib/build> ./examples/tagwriter -g Rock ~/Desktop/test.mp3 
    Leonard: /Users/scott/Projects/taglib/build> framelist ~/Desktop/test.mp3 
    ******************** "/Users/scott/Desktop/test.mp3"********************
    ID3v2.3.0, 1039 bytes in tag
    TCON - "Rock"
    
    ID3v1
    title   - ""
    artist  - ""
    album   - ""
    year    - "0"
    comment - ""
    track   - "0"
    genre   - ""
    
    APE
    file does not have a valid APE tag

Here's the diff:

    diff --git a/examples/tagwriter.cpp b/examples/tagwriter.cpp
    index ed8b0d7a..7c84643b 100644
    --- a/examples/tagwriter.cpp
    +++ b/examples/tagwriter.cpp
    @@ -36,6 +36,7 @@
     #include <tfile.h>
     #include <tag.h>
     #include <tpropertymap.h>
    +#include <mpegfile.h>
     
     using namespace std;
     
    @@ -179,7 +180,10 @@ int main(int argc, char *argv[])
     
       TagLib::List<TagLib::FileRef>::ConstIterator it;
       for(it = fileList.begin(); it != fileList.end(); ++it)
    -    (*it).file()->save();
    +    if(TagLib::MPEG::File *file = dynamic_cast<TagLib::MPEG::File *>(it->file()))
    +      file->save(TagLib::MPEG::File::ID3v2, true, TagLib::ID3v2::v3);
    +    else
    +      (*it).file()->save();
     
       return 0;
     }

What are you doing different?

**Comment by CyberSinh** [comment]
When you open the test.mp3 file with an hexadecimal editor, do you have a genre tag written like `TCON.......9` or `TCON.......(9)`?

**Comment by scotchi** [comment]
Neither.  It uses the full string, "Rock".  That change was made in 2007, which is why I was asking if you're using a very old version.

**Comment by sbooth** [comment]
I didn't realize the `TCON` frame had changed a bit from ID3 v2.3 and v2.4:

**ID3 v2.3:**

TCON
The 'Content type', which previously was stored as a one byte numeric value only, is now a numeric string. You may use one or several of the types as ID3v1.1 did or, since the category list would be impossible to maintain with accurate and up to date categories, define your own. 

References to the ID3v1 genres can be made by, as first byte, enter "(" followed by a number from the genres list (appendix A) and ended with a ")" character. This is optionally followed by a refinement, e.g. "(21)" or "(4)Eurodisco". Several references can be made in the same frame, e.g. "(51)(39)". If the refinement should begin with a "(" character it should be replaced with "((", e.g. "((I can figure out any genre)" or "(55)((I think...)". The following new content types is defined in ID3v2 and is implemented in the same way as the numerig content types, e.g. "(RX)".
RX    Remix
CR    Cover

**ID3 v2.4:**

TCON
   The 'Content type', which ID3v1 was stored as a one byte numeric
   value only, is now a string. You may use one or several of the ID3v1
   types as numerical strings, or, since the category list would be
   impossible to maintain with accurate and up to date categories,
   define your own. Example: "21" $00 "Eurodisco" $00

   You may also use any of the following keywords:
   
     RX  Remix
     CR  Cover


Perhaps `TCON` needs to be handled in `ID3v2::Tag::downgradeFrames()`?

**Comment by CyberSinh** [comment]
You're right @scotchi, genre seems to be written as full string if you specifically overwrite or set it.

But if I save the "BEFORE..." attached MP3 file (without touching the tag genre), the TCON frame "(9)" is replaced by "9", although v2.3 is requested in the `save `method.

Before tagging with Taglib:
[BEFORE - Megadeth - Into the Lungs of Hell.mp3.zip](https://github.com/taglib/taglib/files/5361098/BEFORE.-.Megadeth.-.Into.the.Lungs.of.Hell.mp3.zip)

After tagging with Taglib:
[AFTER - Megadeth - Into the Lungs of Hell.mp3.zip](https://github.com/taglib/taglib/files/5361102/AFTER.-.Megadeth.-.Into.the.Lungs.of.Hell.mp3.zip)

Hope this helps.

PS: the ".zip" extension in the filename is fake, Github disallows MP3 file uploading.

**Comment by CyberSinh** [comment]
Thank you very much @scotchi for the fix!
