### ISSUE TITLE
Compiled TagLib framework for OS X fails at codesign

### ISSUE THREAD

**Issue by beeb** [taglib/taglib#667]
I created a framework from the v1.9.1 source code with the following cmake:

`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FRAMEWORK=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 -DCMAKE_OSX_ARCHITECTURES="x86_64"`

I then drag-and-dropped the tag.framework file (folder) from /Library/Frameworks/ into my Xcode 7.0 project, ticked the "Copy files if needed" checkbox and checked that the file was indeed present in my project folder. I then added the framework to the "Embedded Binaries", which automatically also adds it to "Linked Frameworks and Libraries". I checked that the framework was present in the Build Phases under the "Link binary with libraries" and "Embed frameworks" sections.

I can link to the header files with no error from Xcode (i.e. `#include <tag/mpegfile.h>`) but when I try to compile, I get an error: `Command /usr/bin/codesign failed with exit code 1`

The compiler gives the following additional info: `/Users/valentin/Library/Developer/Xcode/DerivedData/Squeed-gsytetlenuelapbdgypechfnxbht/Build/Products/Debug/Squeed.app/Contents/Frameworks/tag.framework/Versions/A: No such file or directory`

I went and looked in the framework and, indeed, there is no "A" folder in the Versions, but a "1.14.0" folder.. Why is the compiler trying to look at a version that's not there?

Thanks !

**Comment by beeb** [comment]
I managed to compile by changing a line in the file `taglib/CMakeLists.txt`, around line 344 (for taglib-1.10beta at least, I changed to the beta in the mean time).
So `VERSION ${TAGLIB_SOVERSION_MAJOR}.${TAGLIB_SOVERSION_MINOR}.${TAGLIB_SOVERSION_PATCH}` becomes `VERSION "A"`.

I have absolutely no idea why Xcode goes looking for a version "A" but there you go..

**Comment by lalinsky** [comment]
Going by this https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/VersionInformation.html#//apple_ref/doc/uid/20002255-97505-TPXREF102 I assume that "A" is the default major version (Apple itself uses "A", "B", ... for their own frameworks).

Normal version numbers should work as well. One major misunderstanding is that the framework version should only include the major version number. So we should be still on TagLib "1". That should be fixed in CMakeLists.txt.

I guess you might need to configure Xcode somehow to tell it which version to use. But this is all coming from a person who does not develop on OS X, so it's all just theory. :)

**Comment by beeb** [comment]
Yeah the options that can be applied to a compiled framework are very scarce, not sure you can do that in Xcode. I had to use a command line tool to change the install path of the framework once it was compiled (to make it dynamic instead of the static absolute path of where I built it).

**Comment by charlieMonroe** [comment]
@beeb - I'm running into the same issue - would you mind posting what exactly have you changed and where? It would save me a lot of time... Thanks!

**Comment by beeb** [comment]
@charlieMonroe sure, here's what I did:

First look for `set_target_properties(tag PROPERTIES` in `taglib/CMakeLists.txt` (line 343) and change the properties `VERSION` and `SOVERSION` to `"A"` (not sure you need to change both, but just to be sure I changed both)

Then this is the `cmake` command I used:

    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FRAMEWORK=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 -DCMAKE_OSX_ARCHITECTURES="x86_64"

(notes: I'm developing on OS X 10.11 so I used that SDK and the target can be modified. I targetted 10.10 and newer)

Finally, `cd` into the directory that contains tag.framework and do:

    install_name_tool -id @rpath/tag.framework/Versions/A/tag tag.framework/Versions/A/tag

**Comment by charlieMonroe** [comment]
Thanks! I have also found out that you can bypass this by using the CMake GUI app to generate an Xcode project and then changing a few build settings. (You can then embed the Xcode project in yours and it will automatically compile and embed the framework.)

Unfortunately, both solutions require some manual modification with each build (assuming you rebuild only with new commits). I am not very familiar with cmake, but I believe this should be fixable by some conditional settings in `CMakeLists.txt` - when building a framework on OS X, change the version to `A`...

**Comment by jonsteinmetz** [comment]
I apologize if this is somewhat off topic but using both the command line methods and the CMake.app to try and make a framework I still get a build environment that makes a static library.
For example, if I try:
```
cmake -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_FRAMEWORK=ON \
    -DCMAKE_C_COMPILER=/usr/bin/gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
    -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/ \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
    -DCMAKE_OSX_ARCHITECTURES="x86_64"
```
Followed by `make`, I get a static library created and not a framework. Is there something else I am missing to make a framework?
Thanks

**Comment by charlieMonroe** [comment]
@jonsteinmetz - to be honest, I don't remember 100%, but you need to make changes in the Xcode project's build settings manually.

**Comment by FestusHagen** [comment]
Try adding **`BUILD_SHARED_LIBS=On`** to your cmake line ...

**Comment by jonsteinmetz** [comment]
@FestusHagen Excellent, that appears to work, thank you. Would the appropriate thing to do be to open a new issue against the documentation which omits this? Another possibility is that this should not be required and the problem lies elsewhere.

**Comment by tattwamasi** [comment]
I could have sworn this was fixed in a more recent version of TagLib, but I guess I was mistaken.
Here's my comments on it from a year ago on [StackOverflow](http://stackoverflow.com/a/29644894/4646301) 

Given it is still an issue, would someone that's already fixed it like to commit / do a pull request?  If not, and if it would be welcomed, I suppose I could take a shot at it, though CMake is not something I've dealt with much.  It would be nice to have the defaults work out of the box without having to fix the framework and rpath manually. As is every OS X dev trying to use it goes through this same discovery process.

**Comment by beeb** [comment]
Just wanted to say that I was not able to compile a framework with v1.11beta2. Even though I have the `-DBUILD_FRAMEWORK=ON` option enabled it produces a `taglib.a` file. Has anyone tried building a framework with 1.11?

**Comment by tattwamasi** [comment]
@beeb look a couple comments up, for @FestusHagen's reply to @jonsteinmetz comment/question.
I have built a framework from 1.11b2 + 8 using the BUILD_SHARED_LIBS=On along with the BUILD_FRAMEWORK=ON

**Comment by beeb** [comment]
Ooop my bad @tattwamasi thanks

**Comment by tattwamasi** [comment]
In the <taglib base>/taglib/CMakeLists.txt file (not the project CMakeLists.txt file), if you modify the 
if(BUILD_FRAMEWORK) section at the bottom to be as follows:
```
if(BUILD_FRAMEWORK)
  set(BUILD_SHARED_LIBS On)
  set(CMAKE_MACOSX_RPATH 1)
  unset(INSTALL_NAME_DIR)
  set_target_properties(tag PROPERTIES 
      FRAMEWORK TRUE
      MACOSX_RPATH 1
      VERSION "A"
      SOVERSION "A"
      )
endif()

```
Then it appears to build a framework properly, with correct links and correct @rpath internally.
notes:
The `set(BUILD_SHARED_LIBS On)` line is to avoid having to remember telling it to cmake on the command line.  If you put it in the set_target_properties instead, it doesn't work properly - doesn't make the tag symbolic link in the base of the tag.framework
The `set(CMAKE_MACOSX_RPATH 1)` may be redundant with the target property set.  I saw an example written like this, so I used it.  Didn't try it without it.  I did try it without the target property set, and it didn't silence the cmake warning about MACOSX_RPATH behavior, so I put both in. (or maybe it was the other way around)
The `unset(INSTALL_NAME_DIR)` is because if that property is set it will override the rpath install behavior, and it was set just above this section.
The VERSION property seems to be what controls the directory names when building the tag.framework.  I tried it with just the SOVERSION set, and it didn't change the framework directory names.  I left the SOVERSION set, not knowing anything better to do with it :-)

Last note, this just fixes the tag framework, and there is still the tag_c framework build that's also not being built right.  And it looks like the `set(BUILD_SHARED_LIBS On)` line in the tag CMakeLists.txt file is also affecting the whole build, including the tag_c target, because I saw the tag_c framework get built differently when I added that line vs. not (same as on the cmake command line or not).  That makes me think it's not the proper place to put those sets - basically this all reflects that I don't know what I'm doing with cmake.

I kind of wonder if framework (and therefore also shared lib) should be the default on OS X.  Seems like the most likely and common way one would want to use the project.  That would change build behavior though.  And I don't know what the right thing to do about the bindings would be - does it make sense to build a tag_c framework, and should that be tied in with the tag.framework with the BUILD_FRAMEWORK flag, as it is currently?

Things for the maintainer(s) and list to consider I suppose, but until then at least this issue has enough help in it to get people past this step, in a couple different ways.

**Comment by beeb** [comment]
Hello again,

@tattwamasi thanks for the tips, but I tried your solution (with no `DBUILD_SHARED_LIBS` or `BUILD_SHARED_LIBS` in the command) and cmake still produced a `libtag.a` file and no framework.

On the other hand, if I produce the framework with `DBUILD_SHARED_LIBS=On`, then fix the `@rpath` with `install_name_tool` like I've always done (before 1.11), then the Mac App Store guys found that the app crashes upon launch on other systems than mine. The crash report says:

`Dyld Error Message:
  Library not loaded: /usr/local/lib/libboost_atomic-mt.dylib
  Referenced from: /Applications/MyApp.app/Contents/Frameworks/tag.framework/Versions/A/tag
  Reason: image not found`

**Comment by haoxi911** [comment]
Anyone would help to commit @tattwamasi's changes into /taglib/CMakeLists.txt file, especially the rpath fix? Without this fix, the tag.framework may lead some crashes in customer's side but still look good in developer's side. Thanks!

**Comment by haoxi911** [comment]
@beeb I meet exactly same problem on `libboost_atomic-mt.dylib`, and it crashes the application on Sierra immediately after launch. I appreciate for sharing your workaround in your comments!

**Comment by TsudaKageyu** [comment]
I think I understood the problem. I admit that it's bad to depend on Boost's dynamic libraries...
I will remove the dependency on Boost's dynamic libraries.

**Comment by haoxi911** [comment]
@tattwamasi @beeb I made the fixes [here](https://github.com/haoxi911/taglib/commit/b5115e3497328d80a9accf8c1c303374ec36e884). Can you please review and test? Please feel free to let me know if anything is wrong, and I will send a PR later if it is good. Thanks!

**Comment by haoxi911** [comment]
@TsudaKageyu Thank you, can you please take a look at my fixes (I am not quite familar with CMake).

**Comment by scotchi** [comment]
I'd actually go further and say that it'd be a good idea to remove run-time linkage to Boost altogether.  It's presumably not being packaged as a dependency on Linux, which is the only other place that it'd be used as a shared library.  (And historically one of the advantage of TagLib was that other than zlib it had no external dependencies.)

**Comment by haoxi911** [comment]
Agreed, please feel free to revise PR #784 and remove `HAVE_BOOST_ATOMIC` feature.

**Comment by beeb** [comment]
@haoxi911 looks good to me! I was able to compile on Sierra even though libboost_atomic-mt was present in my path, which used to fail.
I tested the generated framework in my app and it didn't show any error or crash so I'm guessing it's all good.

One note that is kind of unrelated, but I remember having to write down a bundle identifier in the framework's `Info.plist` otherwise uploading to iTunes connect would fail. I haven't been able to test after the fix but it's a simple fix anyway.

**Comment by haoxi911** [comment]
@beeb Thanks! We are actually distributing our Mac app outside of AppStore, so we didn't observe this problem yet.

It seems we need to define a bundle identifier for `tag.framework`, thinking it should be something like `org.{organization_name}.tag`.
