### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#710]
I have received some emails asking when we would release the next version. (v1.11?)

Though it's only two months since we released v1.10, we have fixed several bugs and merged a lot of long-standing pull requests. So I think we can release the next beta version now.

**Comment by zhjb7** [comment]
when release Taglib2 :)

**Comment by lalinsky** [comment]
Kageyu, I think you are the only person right now who can do releases. I'm sorry, but I didn't follow any of the changes since 1.10. 

This is my normal release procedure:

 - Finish change log in `NEWS`
 - Change the normal version number and SO version number in `CMakeLists.txt` (there are steps for changing the SO version number, just follow them one-by-one)
 - Change the version number in `taglib/toolkit/taglib.h`
 - Commit everything, create a new tag (`git tag v1.11`), push the tag (`git push origin --tags`)
 - Create a release tar.gz file (`git archive --format=tar --prefix=taglib-1.11/ v1.11 | gzip >taglib-1.11.tar.gz`)
 - Add the release info to the website
  - See the latest commits in https://github.com/taglib/taglib.github.com
  - Add the new release to `_includes`
  - Add the new tar.gz file to `releases` and link it in `_includes/files.markdown` 
  - Change `index.markdown` to include the right release
  - Add 1.10 to `older.markdown`
  - Run `_generate_docs` to update the API docs
 - Send an email to the mailing list

**Comment by TsudaKageyu** [comment]
@lalinsky, I'm willing to do those tasks. I was just not sure if I'm eligible for deciding our release schedule.
Privately, I'd like to do an overall review again, and then release the next beta version in early February.

**Comment by TsudaKageyu** [comment]
I'm going to release v1.11 BETA on Saturday, Jan 30.
