### ISSUE TITLE
Cannot get FileRef unless file has an extension

### ISSUE THREAD

**Issue by michihenning** [taglib/taglib#713]
During testing with 1.9.1, I found that, if a file has no extension, the FileRef constructor creates a null FileRef, even if I set the audio properties to Accurate. That's really annoying. If no extension is present, the code should do a deep inspection of the file.

**Comment by supermihi** [comment]
As noted in the [API reference](http://taglib.github.io/api/classTagLib_1_1FileRef_1_1FileTypeResolver.html), the standard `FileTypeResolver` used by `FileRef`is a simple extension-based implementation. For files without extension, you'd need to write your own `FileTypeResolver` that uses a MIME-Type checker; such is NOT provided by taglib, probably because it is heavily OS-dependent, and several solutions exist outside taglib.

Note that `AudioProperties::ReadStyle` has nothing to do with file type detection; it determines how accurately information such as the length of a song are computed.

**Comment by michihenning** [comment]
OK, thanks for letting me know. I'll do my own file instantiation based on mime type then.
