### ISSUE TITLE
License information in the unit tests.

### ISSUE THREAD

**Issue by TsudaKageyu** [taglib/taglib#715]
I found that some of the unit tests have BSD License descriptions in their headers.
https://github.com/taglib/taglib/blob/master/tests/test_list.cpp

Is it just a mistake? If so, I'd like to fix it.

**Comment by scotchi** [comment]
That header is just completely wrong in general.  Almost all of the file was written by @lalinsky, but it lists my copyright.  It was probably copied from the examples/ dir, which *did* originally, intentionally use the BSD license so that if someone wanted to copy the code into a closed-source application that would be fine.

**Comment by lalinsky** [comment]
Yes, I just copied the examples and did not change the header. I'm fine with changing it.

**Comment by TsudaKageyu** [comment]
Done, thanks!
