### ISSUE TITLE
TagLib is rejecting keys longer than 16 characters in APE tags

### ISSUE THREAD

**Issue by amethystAnt** [taglib/taglib#725]
I noticed recently that TagLib doesn't read and write APE items with keys longer than 16 characters. That is not very convenient, because I'd like to set a cover art to an APE tag with the key "Cover Art (Front)", and now I cannot do that. 

When I open a file with a cover art I added to the tag using MP3Edit, I get the following output in the commnad line:
`TagLib: APE::Tag::parse() - Skipped an item due to an invalid key.`

When I run this code:
`PictureFile picture(picturePath.toStdString().c_str());`
`TagLib::APE::Item item("Cover Art (Front)", picture.getData(), true);`
`apeTag->setItem("Cover Art (Front)", item);`
I get this output:
`TagLib: APE::Tag::setItem() - Couldn't set an item due to an invalid key.`
(PictureFile is a class derived from TagLib::File)

The issue is in the function isKeyValid() in apetag.cpp
Why does TagLib behave like that?

**Comment by sbooth** [comment]
It seems that 16 is the recommended key length while 255 is the maximum according to http://wiki.hydrogenaud.io/index.php?title=APE_key

I'm guessing this is a bug.

**Comment by scotchi** [comment]
Yes, there's currently a function called `isKeyValid` that checks to make sure that the length is between 2 and 16 characters, and otherwise returns false.

I was going to say that it's possible that the allowed length has been changed since the implementation was created (since I've seen that happen on other formats), but since the tag format file that's in the repository contains that data, and has been there since 2004, I think it's fair to say that it's just a bug.

**Comment by amethystAnt** [comment]
Actually, this check was added recently, in this commit:
https://github.com/taglib/taglib/commit/c04b24a2f5410ee2f3cb7dc2363ec11ccd19473b

**Comment by TsudaKageyu** [comment]
Merged. Thanks!
