### ISSUE TITLE
passing test for saving images to ID3v2

### ISSUE THREAD

**Issue by 0x00A** [taglib/taglib#734]
I'm trying to find a passing test for saving one or more images to an mp3. I was searching for `ID3v2::AttachedPictureFrame`, but maybe that's the wrong place to start?

*Edit*: I've looked at examples and code snippets everywhere and I can't get anything working that will write image data to mp3 or mp4 files (no errors, no segfaults, etc, just silently failing to do anything). *but* I just noticed that in the `taglib2` branch there is an example of writing image data which *works* -- whats the status on that branch? Any updates on #721 I'd love to help :)

**Comment by 0x00A** [comment]
*Update*: the `taglib2` branch seems to reliably read and write images to the file types I've tested (`mp4`, `mpeg/id3v1`, `mpeg/id3v2`), if the interface in `taglib2` branch (`tag->setPictures(picMap)`) is the direction that v2 is going, I'd be happy to write some tests for it. /cc @TsudaKageyu @MaxLeb @scotchi

:beers:

**Comment by MaxLeb** [comment]
Not sure what the decision is on the direction it is taking ( this is up to @TsudaKageyu  and @scotchi  ) as I wrote this code because I needed it and decided to push it mainstream as it was really missing. 
I do not have time to write tests for it so you are more than welcome to write some tests.

**Comment by 0x00A** [comment]
@TsudaKageyu @scotchi I'm finding the api pretty nice so far, and would love to see this merged into master, any way I could help?

**Comment by scotchi** [comment]
- This can't be merged into master as it's a binary incompatible change
- I'd actually have been against it going into taglib2 since it silently fails for a number of formats

**Comment by scotchi** [comment]
Also, there is a passing test with ID3v2 images, though it's slightly convoluted: `testPropertyInterface2`

Additionally, [this very old example](http://developer.kde.org/~wheeler/files/more-taglib-examples/taglib-set-picture.cpp) still works fine.

**Comment by 0x00A** [comment]
> since it silently fails for a number of formats
Is that something that can be fixed or is it simply going in the wrong direction?

If it's totally off the table, are there any plans for a single interface that abstracts file types (similar to what's in taglib2 at the moment)?

**Comment by scotchi** [comment]
Yes, at present `setProperties` at least returns a list of the properties that it wasn't able to set.  `setPictures` does now.  However, my preference would be to move both of them to:

    bool setProperty(const String &name, const StringList &vaues);
    bool setPicture(const ByteVector &data, const String &mimeType, const String &type = "DEFAULT");

That would seem to capture most of the utility of the generic interface, provide simple feedback on whether the operation was supported or not via the return value, and well, be much simpler.

Right now, the `setPictures` interface appears to mostly be based on the ID3v2 format, which in most cases is severe overkill.  (Off the top of my head, I don't know of any applications that support multiple images for a single music file, much less a list of images for each 15 types of image.)  It also replicates the ID3v2 enum, which isn't forwards-compatible since the enum can't be arbitrarily modified in future versions (which is why the properties interface uses `String` keys).
