### ISSUE TITLE
Default text encoding not changing

### ISSUE THREAD

**Issue by fillobotto** [taglib/taglib#798]
I have a bad encoded file, which does not display correctly Turkish characters in title/artist fields and I supposed it's because it was previously tagged with wrong encoding.

I'm trying to make TagLib fix this issue when rewriting the tag to the file, but it's not able to, the text still displays with encoding problems.

```
TagLib::MPEG::File* f(....);
TagLib::ID3v2::FrameFactory::instance()->setDefaultTextEncoding(String::UTF16);
f->setID3v2FrameFactory(TagLib::ID3v2::FrameFactory::instance());
TagLib::ID3v2::Tag *id3v2 = f->ID3v2Tag(true);

id3v2->setTitle("Öptüm");
f->save();
```
Honestly I'm not really sure whether the problem is the library or just me (in this case just close this issue immediately). I though this code would have been enough to rewrite frames with different encoding.

Here is the file I'm talking about:
[file.zip](https://github.com/taglib/taglib/files/750271/file.zip)

**Comment by scotchi** [comment]
The problem is with the string literal there and TagLib's default string constructor.  TagLib's default `char *` constructor [assumes](http://taglib.org/api/classTagLib_1_1String.html#a7d6ce86cbae946f7bd4113b447c144df) ISO-8859-1, and I'm assuming you're providing UTF-8. You'll need to specify the encoding for it to work:

    id3v2->setTitle(TagLib::String("Öptüm", TagLib::String::UTF8));

In the TagLib 2 brach it would make sense to switch the default encoding assumption to UTF-8, but when TagLib was first being implemented about 12 years ago, most toolkits still assumed that ISO-8859-1 (i.e. "Latin 1") was what string literals would be unless otherwise specified.  In general though, it's a good idea to be explicit about the encoding you're coming from.

**Comment by fillobotto** [comment]
That was the same I attempted also, but the result is the same, believe it or not.
Now I'm going to try branch 2 to see if it's solved.

**Comment by fillobotto** [comment]
Setting the encoding explicitly is correct but the real solution to my personal problem was that I have to `strip()` the tag and create a new one, otherwise the encoding was not correctly overwritten.
