### ISSUE TITLE
TagTool: A commandline tool / interface?

### ISSUE THREAD

**Issue by Ambrevar** [taglib/taglib#854]
As far as I know, TagLib is the only library that can universally and uniformly edit tags _in-place_.
(FFmpeg is also universal and uniform, but it cannot process files in place if I'm not mistaken.)

This is a big deal for obvious performance reasons.
Sadly bindings can be limited for some languages.  I believe this is because of the disparity between the C and the C++ interfaces (correct me if I'm wrong).

This issue has been raised numerous times in different contexts:

- https://github.com/taglib/taglib/issues/649
- https://github.com/taglib/taglib/issues/455
- https://github.com/Ambrevar/demlo/issues/2
- http://lists.gnu.org/archive/html/emms-help/2018-01/msg00002.html

I realize there is no such thing as a commandline version of taglib.  Call it, say, TagTool.

Commandline tools have some advantages over library bindings:

- They can be used from program extensions (such as Emms for Emacs).  Extensions are usually written in a language where it's not convenient to add bindings to libraries.

- Well, they can be used from the commandline :)

I'm not sure exactly how the amount how work it represents.  If easy enough, it would definitely be worthwhile.
Emms already has rolled out its own (limited) commandline interface to taglib: http://git.savannah.gnu.org/cgit/emms.git/tree/src.

My thinking is something more general, that can both print bindings and set them in-place.  Examples:

```
$ tagtool FILE1 FILE2
path=/real/path/to/file1
album=foo1
artist=foo2

path=/real/path/to/file2
album=bar1
artist=bar2
```

JSON output is probably a good idea too:
```
$ tagtool -json FILES...
{
  ...
}
```

Finally, setting arbitrary tags in-place:
```
$ tagtool -set album qux FILES...
```

TagTool would be a definite drop-in replacement for all the others commandline
tools out there that simply don't cut it: most mp3 taggers are broken (mp3info
does not support id3v2), or simply not universal / uniform.

What do you think?

**Comment by Martchus** [comment]
> FFmpeg is also universal and uniform, but it cannot process files in place if I'm not mistaken.

I don't think you're mistaken.

> TagLib is the only library that can universally and uniformly edit tags in-place.

My own [tag editor](https://github.com/Martchus/tageditor) supports in-place editing and of multiple container/tag formats through its own [library](https://github.com/Martchus/tagparser). Since it does not use taglib, the list of supported formats differs.  
It allows to get and set tags of multiple files at once and independently of the format, similar to your examples.

> Well, they can be used from the commandline :)

For that reason, I've even added bash completion.

> JSON output is probably a good idea too

In fact, I recently added a simple JSON export.

---

Of course my tag editor is just [one of many](https://wiki.archlinux.org/index.php/List_of_applications/Multimedia#Audio_tag_editors).

**Comment by scotchi** [comment]
I don't think creating a tool like this is a bad idea, but I see it as out of scope for the TagLib project.  It would obviously be possible to create something like this using TagLib (and the examples directory has a very simple version of such for reading and writing tags).

**Comment by supermihi** [comment]
It would probably be much easier to write such a tool using a binding to a higher-level language, like pytaglib for python (disclaimer: I am the autor of pytaglib). It already includes a command-line tool for *printing* tags, but adding write support should not be too complicated. Things like JSON formatting come out of the box with python.

On the downside, you'd have python as a dependency, which of course is quite heavy.

**Comment by Ambrevar** [comment]
@Martchus: Thank you very much for hinting me at your project, it's a great effort!  It might just be the answer I was looking for.
I'll keep testing.

Regarding the many other tools, I can't think of any that is both commandline interfaced and can replace tags in-place.

**Comment by btuin** [comment]
So I stumbled on this issue since I had the same need, and I did it myself: [https://gitlab.com/btuin2/tagtools]().
It's a command-line tool like You can list or edit the tags of one or more files (title, artist, album, comment, genre, year, and track). It's written in C++.
Disclaimer: I didn't test it thoroughly, so it's possible there are issues.
