### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [taglib/taglib#924]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by scotchi** [comment]
In the future please use the mailing list (taglib-devel@kde.org) for general discussions rather than the issue tracker.

I'm in the process of reviewing issues / pull requests to prepare a release.  My goal is to have a beta tarball in the next week, and then to follow with a release 1-2 weeks later.

**Comment by JonasVautherin** [comment]
Seems like this never happened :see_no_evil:. I just realized that [vlc apparently depends on taglib 1.11.1](https://code.videolan.org/videolan/vlc/-/blob/master/contrib/src/taglib/rules.mak#L3). Not sure if they would consider updating, though, they already have their own patches. I guess I'll make a PR to add yet another patch there :thinking:.

**Comment by scotchi** [comment]
In case this report shows up for others wondering the same, I'll just reference my previous explanation here:

https://github.com/taglib/taglib/issues/864#issuecomment-631874581

Things got better for a couple months, but at present my kids are indefinitely back at home, and I'm at least multiple months away from being able to dedicate multiple days to TagLib.
