### ISSUE TITLE
FLAC, APE - get on empty tag (title/album/...) will create an empty value in properties map

### ISSUE THREAD

**Issue by whatdoineed2do** [taglib/taglib#931]
FLAC:  Querying a common tag value (like title, album, artist etc) that does not exist will create an empty value in the properties map.  This does not happen for mp3,m4a files.

Code to demonstrate:
* force removal of `title` and save file
* print property map shows no `TITLE`
* reopen file and query value of `title`
* show property map before/after call `title()` shows empty `TITLE` entry (**bug**) 
```
#include <iostream>
#include <taglib/mpegfile.h>
#include <taglib/flacfile.h>
#include <taglib/xiphcomment.h>
#include <taglib/tpropertymap.h>

std::ostream& operator<<(std::ostream& os_, const TagLib::PropertyMap&  m)
{
    for (const auto i : m)
    {
        os_ << i.first.toCString() << " {\n";
        for (const auto& j : i.second) {
            os_ << "  " << j << '\n';
        }
        os_ << "}\n";
    }
    return os_;
}


int main(int argc, char *argv[])
{
    if (argc != 2) {
        return 1;
    }
    try
    {
        {
            TagLib::FLAC::File f(argv[1]);
            f.xiphComment()->removeFields("TITLE");
            std::cout << "FIRST (removed title)\n" << f.properties() << "\n";
            f.save();
        }
        {
            TagLib::FLAC::File f(argv[1]);
            std::cout << "SECOND\n" << f.properties() << "\n";
        }
        {

          TagLib::FLAC::File f(argv[1]);
          std::cout << "THIRD\n" << f.properties() << "\n"
                    << "title = '" <<  f.tag()->title() << "'\n"
                    << "FOURTH\n" << f.properties() << "\n";
        }
    }
    catch (const std::exception& ex)
    {
      std::cerr << ex.what() << std::endl;
    }
    return 0;
}
```

**Comment by whatdoineed2do** [comment]
code to demonstrate bug

**Comment by ufleisch** [comment]
What you are complaining about here is a "feature" of the C++ standard library, see [the std::map::operator[] reference](http://www.cplusplus.com/reference/map/map/operator[]/):

> If k does not match the key of any element in the container, the function inserts a new element with that key and returns a reference to its mapped value. Notice that this always increases the container size by one, even if no mapped value is assigned to the element (the element is constructed using its default constructor).

I do not think that this is a brilliant API, but there are ways to work around it, and I do not think that it is a reason to change the behavior of TagLib in a non-compatible way. With a new major release, which can be binary incompatible, the property interface could be improved. If you only need the standard properties (`"TITLE"..."TRACKNUMBER"`) you could use `TagLib::FileRef` instead of `TagLib::FLAC::File` (and `f.tag()->properties()` instead of `f.properties()`) in order to circumvent the described behavior.

**Comment by ufleisch** [comment]
The problem also affects APE tags, it is even worse because not only the `properties()` are changed after getting any tag frame such as `title()`, also `isEmpty()` is wrong for APE tags after that. I also would like to revise my comment from above - this would be true if it affects the map only after accessing the map itself with `operator[]`, but the map is affected by some other operation which is not directly tied to the map. The following check fails for `Ogg::XiphComment` and `APE::Tag` as type for `tag`.

```
    tag.setProperties(PropertyMap());
    CPPUNIT_ASSERT(tag.isEmpty());
    CPPUNIT_ASSERT(tag.properties().isEmpty());
    CPPUNIT_ASSERT_EQUAL(String(""), tag.title());
    CPPUNIT_ASSERT_EQUAL(String(""), tag.artist());
    CPPUNIT_ASSERT_EQUAL(String(""), tag.album());
    CPPUNIT_ASSERT_EQUAL(String(""), tag.comment());
    CPPUNIT_ASSERT_EQUAL(String(""), tag.genre());
    CPPUNIT_ASSERT_EQUAL(0U, tag.track());
    CPPUNIT_ASSERT(tag.isEmpty());
    CPPUNIT_ASSERT(tag.properties().isEmpty());
```

I will enhance the associated merge request with tests and fixes for the APE case.
