### ISSUE TITLE
Method  TagLib::MPEG::File.hasID3v2Tag is misreporting for some test data

### ISSUE THREAD

**Issue by finnianr** [taglib/taglib#943]
Hi, I am creating an [Eiffel binding](http://www.eiffel-loop.com/library/TagLib.html) for TagLib and noticed a problem with `hasID3v2Tag` when using ID3 test data from the project [id3lib](https://github.com/dreamindustries/id3lib). The directory [id3lib/tree/master/examples](https://github.com/dreamindustries/id3lib/tree/master/examples) has a number of test ID3 files. I found that for the following files, `hasID3v2Tag` is returning `False` when in fact they do contain 2.x frames.
```
230-compressed.tag
crc53865.mp3
thatspot.tag
```
Either these files are malformed or `hasID3v2Tag` has a bug.

-- Finnian Reilly

**Comment by ufleisch** [comment]
TagLib can detect the file type by content or extension. Since the two _.tag_ files contain only an ID3v2 tag, but are not real MP3 files, detection by content will not work. You have to rename them to _.mp3_, then you will get the ID3v2 tag with TagLib (e.g. using _examples/tagreader_ or _examples/tagreader_c_).
The file _crc53865.mp3_ does not have an ID3v2 tag, so TagLib is right here. It probably has an MPEG header, but it does not have an MPEG frame (TagLib reports "MPEG::Properties::read() -- Could not find an MPEG frame in the stream."), so it could be considered as malformed.
