### ISSUE TITLE
Saving artwork in FLAC file prevents Windows 10 from displaying the tags

### ISSUE THREAD

**Issue by CyberSinh** [taglib/taglib#954]
Hi,

Saving FLAC files with Taglib covers prevents Windows 10 from displaying the tags in the file explorer, if the image size is a bit heavy.

I have the impression that Windows stops looking for the tags if it doesn't find them at the very beginning of the files. However, it seems that Taglib saves the PICTURE block before the VORBIS_COMMENT block. And if the PICTURE block is too long, the VORBIS_COMMENT block is not found by Windows.

Is it possible to save the VORBIS_COMMENT block just after the STREAMINFO block, before the PICTURE block in FLAC files?

Thank you.

**Comment by ufleisch** [comment]
I can confirm this on Windows 10. For small pictures, it is not a problem, but a size of 1 MB is enough to prevent Windows from displaying the tags. We probably all agree that this should be fixed on Windows, but nevertheless I suggest that TagLib writes the Vorbis Comment block before the picture block in order to improve compatibility. I have made a pull request doing this.

**Comment by ufleisch** [comment]
Fixed with #983.
