### ISSUE TITLE
ID3v2 ChapterFrame strips null terminators from TIT2 embeddedFrames

### ISSUE THREAD

**Issue by odie5533** [taglib/taglib#994]
When I use pytaglib, the saved result has stripped all the null terminators off the ends of the TIT2 subframes in the CHAP frames. The [spec sheet](https://id3.org/id3v2-chapters-1.0) says the TIT2 strings should be null terminated.

https://github.com/taglib/taglib/blob/master/tests/test_id3v2.cpp#L1355
In this test I think it should be `"CH1\x00"`, and the prior size ints adjusted to account for the extra byte.

**Comment by ufleisch** [comment]
If I read the spec, I would say you are right. It explicitly states "Null terminated string" for the embedded sub frames of the CHAP and CTOC frames. _id3v2.4.0-structure.txt_ also mentions "Terminated with $00" in the list of possible encodings. _id3v2.4.0-frames.txt_ explicitly mentions "terminated strings", which implies that also "non-terminated strings" exist. And _id3v2.3.0.txt_ even says in 4.2. (Text information frames) "If the textstring is followed by a termination ($00 (00))", which I would interpret as "not all text strings are terminated". The frame descriptions always explicitly show the content with `<text string according to encoding> $00 (00)` or `<text string according to encoding>`, and I would say that in the latter case (which also includes all text information frames, which are the most common types of frames used), a zero termination is not needed. It is actually only needed if the string boundaries cannot be determined by some other means such as a length field (see also the treatise about the "two strategies" in [Practical: An ID3 Parser](http://www.gigamonkeys.com/book/practical-an-id3-parser.html)). Since it does not make sense to treat the sub frames in CTOC and CHAP differently than the other frames, I would conclude that we should not change this.
By the way: I have a collection of MP3 files tagged with different tools for testing purposes and it seems that the large majority of tools (with the exception of iTunes and exfalso) does not append null terminators.

**Comment by odie5533** [comment]
Thank you for the detailed response. I completely agree with your interpretation and was unfamiliar with the rest of the spec.

Part of me still would prefer if a tagger wasn't in the habit of rewriting tags that it wasn't asked to and which are valid. Has this behavior been considered?

**Comment by scotchi** [comment]
That isn't really practical with the model that TagLib uses, and would be a significant undertaking (for not a lot of benefit):  like most parsers (same, e.g. with a DOM model), TagLib parses in incoming data into an its internal data structures and then on save renders them from those data structures to binary data.  It doesn't have an intermediate layer that tracks the original parsed data.
